/*
	ArmA 3 Fishers Life
	Code written by ArmA 3 Fishers Life Development Team
	@Copyright ArmA 3 Fishers Life (https://www.arma3fisherslife.net)
	YOU ARE NOT ALLOWED TO COPY OR DISTRIBUTE THE CONTENT OF THIS FILE WITHOUT AUTHOR AGREEMENT
	More informations : https://www.bistudio.com/community/game-content-usage-rules
*/

Config_Items =
[
	["waterbottle",localize"STR_ConfigItems_WaterBottle", 0.5, "A3PL_BottlePlastic_V2",0,true,true,true, true, true,"A3PL_Items_Thirst", [0,0,0], ""],
	["waterbottlempty",localize"STR_ConfigItems_waterbottlempty", 0.1, "A3PL_BottlePlastic_V2",0,true,true,true, true, true,"", [0,0,0], ""],
	["wood_barrier",localize"STR_ConfigItems_wood_barrier",3,"A3PL_RoadBarrier",0,true,true,true,false,false,"", [0,0,0], ""],
	["plastic_barrier_small",localize"STR_ConfigItems_plastic_barrier_small",3,"A3PL_PlasticBarrier_01",0,true,true,true,false,false,"", [0,0,0], ""],
	["plastic_barrier_large",localize"STR_ConfigItems_plastic_barrier_large",3,"A3PL_PlasticBarrier_02",0,true,true,true,false,false,"", [0,0,0], ""],
	["jerrycan_empty",localize"STR_ConfigItems_jerrycan_empty",4,"A3PL_Jerrycan",-90,true,true,true,true,true,"", [0,0,0], ""],
	["SMG_Part_Stock",localize"STR_ConfigItems_SMG_Part_Stock",8,"A3PL_Crate",-90,true,true,true,false,false,"", [0,0,0], ""],
	["SMG_Part_Body",localize"STR_ConfigItems_SMG_Part_Body",10,"A3PL_Crate",-90,true,true,true,false,false,"", [0,0,0], ""],
	["SMG_Part_Grip",localize"STR_ConfigItems_SMG_Part_Grip",5,"A3PL_Crate",-90,true,true,true,false,false,"", [0,0,0], ""],
	["SMG_Part_Trigger",localize"STR_ConfigItems_SMG_Part_Trigger",5,"A3PL_Crate",-90,true,true,true,false,false,"", [0,0,0], ""],
	["SMG_Part_Barrel",localize"STR_ConfigItems_SMG_Part_Barrel",5,"A3PL_Crate",-90,true,true,true,false,false,"", [0,0,0], ""],
	["matches",localize"STR_ConfigItems_matches", 0.5, "A3PL_Seed_Corn",0,true,true,true, true, true,"", [0,0,0], ""],

	["zipties",localize"STR_ConfigItems_zipties", 1, "A3PL_Handcuffs", 0, true, true, true, true, true, "", [0,0,0], ""],

	["dirty_cash",localize"STR_ConfigItems_dirty_cash", 0.0005, "A3PL_Money", 0, true, true, true, true, true, "", [0,0,0], ""],
	["dildo",localize"STR_ConfigItems_dildo",0.1,"A3PL_Dildo",0,true,true,true,true,true,"", [0,0,0], ""],

	["v_lockpick",localize"STR_ConfigItems_v_lockpick",0.1,"A3PL_Grinder",0,true,true,true,true,true,"", [0,0,0], ""],
	["keycard",localize"STR_ConfigItems_keycard",0.1,"A3PL_Lockpick",0,true,true,true,true,true,"", [0,0,0], ""],

	["pizzabites",localize"STR_ConfigItems_pizzabites", 0.1, "A3PL_PartyPack",0,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["soupcup",localize"STR_ConfigItems_soupcup", 0.1, "A3PL_MaggiiNoodle",0,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["cookies",localize"STR_ConfigItems_cookies", 0.1, "A3PL_Timtams",0,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["applecookies",localize"STR_ConfigItems_applecookies", 0.1, "A3PL_Timtams",0,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["cereal",localize"STR_ConfigItems_cereal", 0.2, "A3PL_WeetBix", 90, true, true, true, true, true, "A3PL_Items_Food", [0,0,0], ""],
	["bread",localize"STR_ConfigItems_bread", 0.2, "A3PL_Bread", 90, true, true, true, true, true, "A3PL_Items_Food", [0,0,0], ""],
	["generator",localize"STR_ConfigItems_generator", 15, "A3PL_Generator",0,true,true,true,false,false,"", [0,0,0], ""],
	["flag1",localize"STR_ConfigItems_flag1", 15, "A3PL_Flag1",0,true,true,true,false,false,"", [0,0,0], ""],
	["flag2",localize"STR_ConfigItems_flag2", 15, "A3PL_Flag2",0,true,true,true,false,false,"", [0,0,0], ""],
	["distillery",localize"STR_ConfigItems_distillery", 15, "A3PL_Distillery",0,true,true,true,false,false,"", [0,0,0], ""],
	["distillery_hose",localize"STR_ConfigItems_distillery_hose", 5, "A3PL_Distillery_Hose",0,true,true,true,false,false,"", [0,0,0], ""],
	["jug",localize"STR_ConfigItems_jug", 3, "A3PL_Jug",0,true,true,true, true, true,"", [0,0,0], ""],
	["jug_moonshine",localize"STR_ConfigItems_jug_moonshine", 3, "A3PL_Jug_Corked",0,true,true,true, true, true,"", [0,0,0], ""],
	["jug_green",localize"STR_ConfigItems_jug_green", 3, "A3PL_Jug_Green",0,true,true,true, true, true,"", [0,0,0], ""],
	["jug_green_moonshine",localize"STR_ConfigItems_jug_green_moonshine", 5, "A3PL_Jug_Green_Corked",0,true,true,true, true, true,"", [0,0,0], ""],
	["malt",localize"STR_ConfigItems_malt", 3, "A3PL_Grainsack_Malt",0,true,true,true,false,false,"", [0,0,0], ""],
	["yeast",localize"STR_ConfigItems_yeast", 3, "A3PL_Grainsack_Yeast",0,true,true,true,false,false,"", [0,0,0], ""],
	["cornmeal",localize"STR_ConfigItems_cornmeal", 3, "A3PL_Grainsack_CornMeal",0,true,true,true,false,false,"", [0,0,0], ""],
	["wheat",localize"STR_ConfigItems_wheat", 0.1, "A3PL_Sack",0,true,true,true, true, true,"", [0,0,0], ""],
	["log",localize"STR_ConfigItems_log", 5, "A3PL_WoodenLog",0,true,true,true,false,false,"", [0,0,0], ""],
	["planter",localize"STR_ConfigItems_planter", 10, "A3PL_Planter2",0,true,true,true,false,false,"", [0,0,0], ""],
	["workbench",localize"STR_ConfigItems_workbench", 10, "A3PL_WorkBench",0,true,true,true,false,true,"", [0,0,0], ""],
	["table","Table", 10, "A3FL_Table",0,true,true,true,false,true,"", [0,0,0], ""],
	["lamp_200w",localize"STR_ConfigItems_lamp_200w", 5, "A3PL_Cannabis_Lamp_200W",0,true,true,true,false,true,"", [0,0,0], ""],
	["lamp_500w",localize"STR_ConfigItems_lamp_500w", 5, "A3PL_Cannabis_Lamp_500W",0,true,true,true,false,true,"", [0,0,0], ""],
	["lamp_1000w",localize"STR_ConfigItems_lamp_1000w", 5, "A3PL_Cannabis_Lamp_1000W",0,true,true,true,false,true,"", [0,0,0], ""],
	["fan",localize"STR_ConfigItems_fan", 5, "A3PL_Fan",0,true,true,true,false,false,"", [0,0,0], ""],
	["grinder",localize"STR_ConfigItems_grinder", 3, "A3PL_Mixer",0,true,true,true,false,false,"", [0,0,0], ""],
	["scale",localize"STR_ConfigItems_scale", 3, "A3PL_Scale",0,true,true,true,false,false,"", [0,0,0], ""],
	["pavilion",localize"STR_ConfigItems_pavilion", 0.1, "A3PL_Pavilion",0,true,true,true,false,false,"", [0,0,0], ""],
	["cannabis_bud",localize"STR_ConfigItems_cannabis_bud", 0.25, "A3PL_Cannabis_Bud",0,true,true,true, true, true,"", [0,0,0], ""],
	["cannabis_bud_cured",localize"STR_ConfigItems_cannabis_bud_cured", 0.25, "A3PL_Cannabis_Bud",0,true,true,true, true, true,"", [0,0,0], ""],
	["marijuana",localize"STR_ConfigItems_marijuana",1,"A3PL_MarijuanaBag",0,true,true,true, true, true,"", [0,0,0], ""],
	["cannabis_grinded_5g",localize"STR_ConfigItems_cannabis_grinded_5g", 0.25, "A3PL_Cannabis_Bud",0,true,true,true, true, true,"", [0,0,0], ""],
	["weed_5g",localize"STR_ConfigItems_weed_5g",1,"A3PL_MarijuanaBag",5,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_10g",localize"STR_ConfigItems_weed_10g",1,"A3PL_MarijuanaBag",10,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_15g",localize"STR_ConfigItems_weed_15g",1,"A3PL_MarijuanaBag",15,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_20g",localize"STR_ConfigItems_weed_20g",1,"A3PL_MarijuanaBag",20,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_25g",localize"STR_ConfigItems_weed_25g",1,"A3PL_MarijuanaBag",25,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_30g",localize"STR_ConfigItems_weed_30g",1,"A3PL_MarijuanaBag",30,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_35g",localize"STR_ConfigItems_weed_35g",1,"A3PL_MarijuanaBag",35,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_40g",localize"STR_ConfigItems_weed_40g",1,"A3PL_MarijuanaBag",40,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_45g",localize"STR_ConfigItems_weed_45g",1,"A3PL_MarijuanaBag",45,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_50g",localize"STR_ConfigItems_weed_50g",1,"A3PL_MarijuanaBag",50,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_55g",localize"STR_ConfigItems_weed_55g",1,"A3PL_MarijuanaBag",60,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_60g",localize"STR_ConfigItems_weed_60g",1,"A3PL_MarijuanaBag",70,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_65g",localize"STR_ConfigItems_weed_65g",1,"A3PL_MarijuanaBag",75,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_70g",localize"STR_ConfigItems_weed_70g",1,"A3PL_MarijuanaBag",80,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_75g",localize"STR_ConfigItems_weed_75g",1,"A3PL_MarijuanaBag",95,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_80g",localize"STR_ConfigItems_weed_80g",1,"A3PL_MarijuanaBag",96,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_85g",localize"STR_ConfigItems_weed_85g",1,"A3PL_MarijuanaBag",97,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_90g",localize"STR_ConfigItems_weed_90g",1,"A3PL_MarijuanaBag",98,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_95g",localize"STR_ConfigItems_weed_95g",1,"A3PL_MarijuanaBag",99,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["weed_100g",localize"STR_ConfigItems_weed_100g",1,"A3PL_MarijuanaBag",100,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["roadcones",localize"STR_ConfigItems_roadcones", 10, "A3PL_RoadCone_x10",0,true,true,true,false,true,"", [0,0,0], ""],
	["roadcone",localize"STR_ConfigItems_roadcone", 1, "A3PL_RoadCone",0,true,true,true,false,false,"", [0,0,0], ""],
	["seed_coca",localize"STR_ConfigItems_seed_coca", 0.5, "A3PL_Seed_Corn",0,true,true,true, true, true,"", [0,0,0], ""],
	["seed_sugar",localize"STR_ConfigItems_seed_sugar", 0.5, "A3PL_Seed_Corn",0,true,true,true, true, true,"", [0,0,0], ""],
	["coca",localize"STR_ConfigItems_coca", 0.5, "A3PL_Seed_Corn",0,true,true,true, true, true,"", [0,0,0], ""],
	["sugarcane",localize"STR_ConfigItems_sugarcane", 0.5, "A3PL_Seed_Corn",0,true,true,true, true, true,"", [0,0,0], ""],
	["coke",localize"STR_ConfigItems_coke", 0.5, "A3PL_Can_V2",0,true,true,true, true, true,"A3PL_Items_Thirst", [0,0,0], ""],
	["jerrycan",localize"STR_ConfigItems_jerrycan",30,"A3PL_Jerrycan",-90,true,true,true,true,true,"", [0,0,0], ""],
	["candy",localize"STR_ConfigItems_candy", 0.1, "A3PL_hw_candybucket",0,true,true,true,true,true,"", [0,0,0], ""],
	["cauldron",localize"STR_ConfigItems_cauldron", 10, "A3PL_hw_cauldron",0,true,true,true,false,false,"", [0,0,0], ""],
	["skeletoncauldron",localize"STR_ConfigItems_skeletoncauldron", 0.1, "Land_A3PL_hw_skeletonCauldron",0,true,true,true,false,false,"", [0,0,0], ""],
	["lantern",localize"STR_ConfigItems_lantern", 0.1, "A3PL_hw_lantern",0,true,true,true,true,true,"", [0,0,0], ""],
	["pumpkin_green",localize"STR_ConfigItems_pumpkin_green", 0.1, "Land_A3PL_hw_pumpkin_green",0,true,true,true,false,false,"", [0,0,0], ""],
	["pumpkin_orange",localize"STR_ConfigItems_pumpkin_orange", 0.1, "Land_A3PL_hw_pumpkin_orange",0,true,true,true,false,false,"", [0,0,0], ""],
	["pumpkin_red",localize"STR_ConfigItems_pumpkin_red", 0.1, "Land_A3PL_hw_pumpkin_red",0,true,true,true,false,false,"", [0,0,0], ""],
	["pumpkinhat_red",localize"STR_ConfigItems_pumpkinhat_red", 0.1, "Land_A3PL_hw_pumpkinhat_red",0,true,true,true,false,false,"", [0,0,0], ""],
	["pumpkinhat_orange",localize"STR_ConfigItems_pumpkinhat_orange", 0.1, "Land_A3PL_hw_pumpkinhat_orange",0,true,true,true,false,false,"", [0,0,0], ""],
	["pumpkinhat_green",localize"STR_ConfigItems_pumpkinhat_green", 0.1, "Land_A3PL_hw_pumpkinhat_green",0,true,true,true,false,false,"", [0,0,0], ""],
	["girlstatue",localize"STR_ConfigItems_girlstatue", 0.1, "Land_A3PL_Girlstatue",0,true,true,true,false,false,"", [0,0,0], ""],
	["diamond",localize"STR_ConfigItems_diamond",1,"A3PL_Diamond",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_alex",localize"STR_ConfigItems_diamond_alex",0.5,"A3PL_Diamond_Alex",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_aqua",localize"STR_ConfigItems_diamond_aqua",0.5,"A3PL_Diamond_Aqua",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_emerald",localize"STR_ConfigItems_diamond_emerald",0.5,"A3PL_Diamond_Emerald",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_ruby",localize"STR_ConfigItems_diamond_ruby",0.5,"A3PL_Diamond_Ruby",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_sapphire",localize"STR_ConfigItems_diamond_sapphire",0.5,"A3PL_Diamond_Sapphire",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_tourmaline",localize"STR_ConfigItems_diamond_tourmaline",0.5,"A3PL_Diamond_Tourmaline",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_ill",localize"STR_ConfigItems_diamond_ill",1,"A3PL_Diamond",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_alex_ill",localize"STR_ConfigItems_diamond_alex_ill",0.5,"A3PL_Diamond_Alex",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_aqua_ill",localize"STR_ConfigItems_diamond_aqua_ill",0.5,"A3PL_Diamond_Aqua",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_emerald_ill",localize"STR_ConfigItems_diamond_emerald_ill",0.5,"A3PL_Diamond_Emerald",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_ruby_ill",localize"STR_ConfigItems_diamond_ruby_ill",0.5,"A3PL_Diamond_Ruby",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_sapphire_ill",localize"STR_ConfigItems_diamond_sapphire_ill",0.5,"A3PL_Diamond_Sapphire",0,true,true,true,true,true,"", [0,0,0], ""],
	["diamond_tourmaline_ill",localize"STR_ConfigItems_diamond_tourmaline_ill",0.5,"A3PL_Diamond_Tourmaline",0,true,true,true,true,true,"", [0,0,0], ""],
	["furn_chair1",localize"STR_ConfigItems_furn_chair1",6,"A3PL_Chair1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_chair2",localize"STR_ConfigItems_furn_chair2",6,"A3PL_Chair2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_chair3",localize"STR_ConfigItems_furn_chair3",6,"A3PL_Chair3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_chair4",localize"STR_ConfigItems_furn_chair4",6,"A3PL_Chair4",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_bed1",localize"STR_ConfigItems_furn_bed1",6,"A3PL_Bed1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_bed2",localize"STR_ConfigItems_furn_bed2",6,"A3PL_Bed2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_cabinet1",localize"STR_ConfigItems_furn_cabinet1",6,"A3PL_Cabinet1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_cabinet2",localize"STR_ConfigItems_furn_cabinet2",6,"A3PL_Cabinet2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_cabinet3",localize"STR_ConfigItems_furn_cabinet3",6,"A3PL_Cabinet3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_coffeetable1",localize"STR_ConfigItems_furn_coffeetable1",6,"A3PL_coffeeTable1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_coffeetable2",localize"STR_ConfigItems_furn_coffeetable2",6,"A3PL_coffeeTable2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_coffeetable3",localize"STR_ConfigItems_furn_coffeetable3",6,"A3PL_coffeeTable3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_coffeetable4",localize"STR_ConfigItems_furn_coffeetable4",6,"A3PL_coffeeTable4",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_cornersofa",localize"STR_ConfigItems_furn_cornersofa",6,"A3PL_CornerSova",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_dryingtowel",localize"STR_ConfigItems_furn_dryingtowel",6,"A3PL_DryingTowel",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_flasket",localize"STR_ConfigItems_furn_flasket",6,"A3PL_Flasket",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_kitchenchair1",localize"STR_ConfigItems_furn_kitchenchair1",6,"A3PL_KitchenChair1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_kitchenchair2",localize"STR_ConfigItems_furn_kitchenchair2",6,"A3PL_KitchenChair2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_kitchenshelf1",localize"STR_ConfigItems_furn_kitchenshelf1",6,"A3PL_KitchenShelf1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_kitchenshelf2",localize"STR_ConfigItems_furn_kitchenshelf2",6,"A3PL_KitchenShelf2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_kitchenshelf3",localize"STR_ConfigItems_furn_kitchenshelf3",6,"A3PL_KitchenShelf3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_kitchenshelfcorner",localize"STR_ConfigItems_furn_kitchenshelfcorner",6,"A3PL_KitchenShelfCorner",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_kitchentable1",localize"STR_ConfigItems_furn_kitchentable1",6,"A3PL_KitchenTable1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_kitchentable2",localize"STR_ConfigItems_furn_kitchentable2",6,"A3PL_KitchenTable2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_lamp1",localize"STR_ConfigItems_furn_lamp1",6,"A3PL_Lamp1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_lamp2",localize"STR_ConfigItems_furn_lamp2",6,"A3PL_Lamp2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mirror",localize"STR_ConfigItems_furn_mirror",6,"A3PL_Mirror",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_modkitchen1",localize"STR_ConfigItems_furn_modkitchen1",6,"A3PL_ModularKitchen1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_modkitchen2",localize"STR_ConfigItems_furn_modkitchen2",6,"A3PL_ModularKitchen2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_modkitchen3",localize"STR_ConfigItems_furn_modkitchen3",6,"A3PL_ModularKitchen3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_modkitchen4",localize"STR_ConfigItems_furn_modkitchen4",6,"A3PL_ModularKitchen4",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_pouf",localize"STR_ConfigItems_furn_pouf",6,"A3PL_Pouf",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_rack1",localize"STR_ConfigItems_furn_rack1",6,"A3PL_Rack1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_rack2",localize"STR_ConfigItems_furn_rack2",6,"A3PL_Rack2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_sofa4",localize"STR_ConfigItems_furn_sofa4",6,"A3PL_Sofa1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_sofa5",localize"STR_ConfigItems_furn_sofa5",6,"A3PL_Sofa2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_sofa6",localize"STR_ConfigItems_furn_sofa6",6,"A3PL_Sofa3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_sofa7",localize"STR_ConfigItems_furn_sofa7",6,"A3PL_Sofa4",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_table1",localize"STR_ConfigItems_furn_table1",6,"A3PL_table1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_table2",localize"STR_ConfigItems_furn_table2",6,"A3PL_table2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_tvtable1",localize"STR_ConfigItems_furn_tvtable1",6,"A3PL_TvTable1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_tvtable2",localize"STR_ConfigItems_furn_tvtable2",6,"A3PL_TvTable2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_tvtable3",localize"STR_ConfigItems_furn_tvtable3",6,"A3PL_TvTable3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_bed3",localize"STR_ConfigItems_furn_bed3",6,"A3PL_Bed3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_barcabinet",localize"STR_ConfigItems_furn_barcabinet",6,"A3PL_Bar_Cabinet",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_bookshelf",localize"STR_ConfigItems_furn_bookshelf",6,"A3PL_Bookshelf",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_diningchair",localize"STR_ConfigItems_furn_diningchair",6,"A3PL_DiningChair",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_diningtableprops",localize"STR_ConfigItems_furn_diningtableprops",6,"A3PL_DiningTableProps",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_kennel",localize"STR_ConfigItems_furn_kennel",6,"A3PL_Kennel",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_nightstand",localize"STR_ConfigItems_furn_nightstand",6,"A3PL_NightStand",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_nightstandlamp",localize"STR_ConfigItems_furn_nightstandlamp",6,"A3PL_NightStandLamp",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_sofa1",localize"STR_ConfigItems_furn_sofa1",6,"A3PL_Sofa1New",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_sofa3",localize"STR_ConfigItems_furn_sofa3",6,"A3PL_Sofa3New",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_grill",localize"STR_ConfigItems_furn_grill",6,"A3PL_Mcfisher_Grill",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_cabinetdoubletop",localize"STR_ConfigItems_furn_cabinetdoubletop",6,"A3PL_CabinetDoubleTop",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_cabinetsingletop",localize"STR_ConfigItems_furn_cabinetsingletop",6,"A3PL_CabinetSingleTop",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_cabinettopcorner",localize"STR_ConfigItems_furn_cabinettopcorner",6,"A3PL_CabinetTopCorner",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_countercorner",localize"STR_ConfigItems_furn_countercorner",6,"A3PL_CounterCorner",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_counterdoublecabinet",localize"STR_ConfigItems_furn_counterdoublecabinet",6,"A3PL_CounterDoubleCabinet",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_counterdrawer",localize"STR_ConfigItems_furn_counterdrawer",6,"A3PL_CounterDrawer",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_countersinglecabinet",localize"STR_ConfigItems_furn_countersinglecabinet",6,"A3PL_CounterSingleCabinet",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_countertop1",localize"STR_ConfigItems_furn_countertop1",6,"A3PL_CounterTop1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_countertop2",localize"STR_ConfigItems_furn_countertop2",6,"A3PL_CounterTop2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_countertop3",localize"STR_ConfigItems_furn_countertop3",6,"A3PL_CounterTop3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_sinkbigcounter",localize"STR_ConfigItems_furn_sinkbigcounter",6,"A3PL_SinkBigCounter",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_sinksinglecabinet",localize"STR_ConfigItems_furn_sinksinglecabinet",6,"A3PL_SinkSingleCabinet",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_gamer_billiard","inh",6,"A3PL_Gamer_BilliardTable",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_gamer_dartb","inh",6,"A3PL_Gamer_Dartboard",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_gamer_galaga","inh",6,"A3PL_Gamer_Galaga",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_gamer_lcd","inh",6,"A3PL_Gamer_LCD",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_gamer_unicorn","inh",6,"A3PL_Gamer_UnicornFloat",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_statuegod","inh",6,"A3PL_Garden_StatueGod",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_statuegod2","inh",6,"A3PL_Garden_StatueGod2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_statuegod3","inh",6,"A3PL_Garden_StatueGod3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_statuegod4","inh",6,"A3PL_Garden_StatueGod4",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_statuemonk","inh",6,"A3PL_Garden_StatueMonk",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_statueviking","inh",6,"A3PL_Garden_StatueViking",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_statueviking2","inh",6,"A3PL_Garden_StatueViking2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_statuewoman","inh",6,"A3PL_Garden_StatueWoman",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_statuewoman2","inh",6,"A3PL_Garden_StatueWoman2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_statuewoman3","inh",6,"A3PL_Garden_StatueWoman3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_campfire","inh",6,"A3PL_Garden_Campfire",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_treebench","inh",6,"A3PL_Garden_Treebench",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_vineslarge","inh",6,"A3PL_Garden_VinesLarge",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_vinesmedium","inh",6,"A3PL_Garden_VinesMedium",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_garden_vinessmall","inh",6,"A3PL_Garden_VinesSmall",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mancave_bear","inh",6,"A3PL_Mancave_Bearhead",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mancave_deer","inh",6,"A3PL_Mancave_DeerAntlers",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mancave_fox","inh",6,"A3PL_Mancave_FoxHead",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mancave_moose","inh",6,"A3PL_Mancave_MooseHead",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mancave_wolf","inh",6,"A3PL_Mancave_Wolfhead",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mancave_cocktail","inh",6,"A3PL_Mancave_CocktailSign",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mancave_money1","inh",6,"A3PL_Mancave_CosmeticMoney1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mancave_money2","inh",6,"A3PL_Mancave_CosmeticMoney2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mancave_ghost","inh",6,"A3PL_Mancave_GhostbusterSign",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_mancave_globe","inh",6,"A3PL_Mancave_Globe",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_1","inh",6,"A3PL_WallDecor_WallPanel1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_2","inh",6,"A3PL_WallDecor_WallPanel2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_3","inh",6,"A3PL_WallDecor_WallPanel3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_4","inh",6,"A3PL_WallDecor_WallPanel4",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_5","inh",6,"A3PL_WallDecor_WallPanel5",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_6","inh",6,"A3PL_WallDecor_WallPanel6",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_7","inh",6,"A3PL_WallDecor_WallPanel7",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_8","inh",6,"A3PL_WallDecor_WallPanel8",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_9","inh",6,"A3PL_WallDecor_WallPanel9",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_10","inh",6,"A3PL_WallDecor_WallPanel10",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_11","inh",6,"A3PL_WallDecor_WallPanel11",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_12","inh",6,"A3PL_WallDecor_WallPanel12",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_13","inh",6,"A3PL_WallDecor_WallPanel13",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_14","inh",6,"A3PL_WallDecor_WallPanel14",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_walldecor_15","inh",6,"A3PL_WallDecor_WallPanel15",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_antchair","inh",6,"A3PL_Winchester_AntiqueChair",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_antdesk","inh",6,"A3PL_Winchester_AntiqueDesk",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_armchair","inh",6,"A3PL_Winchester_ArmChair",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_bed1","inh",6,"A3PL_Winchester_Bed1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_bed2","inh",6,"A3PL_Winchester_Bed2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_bedside","inh",6,"A3PL_Winchester_Bedside",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chair1","inh",6,"A3PL_Winchester_Chair1",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chair2","inh",6,"A3PL_Winchester_Chair2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chestdraw","inh",6,"A3PL_Winchester_ChestDrawers",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chestdraw2","inh",6,"A3PL_Winchester_ChestDrawers2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chestdraw3","inh",6,"A3PL_Winchester_ChestDrawers3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chestdraw4","inh",6,"A3PL_Winchester_ChestDrawers4",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chestdraw5","inh",6,"A3PL_Winchester_ChestDrawers5",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chestdraw6","inh",6,"A3PL_Winchester_ChestDrawers6",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chestdraw7","inh",6,"A3PL_Winchester_ChestDrawers7",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chestdraw8","inh",6,"A3PL_Winchester_ChestDrawers8",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_chestdraw9","inh",6,"A3PL_Winchester_ChestDrawers9",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_floorlamp","inh",6,"A3PL_Winchester_Floorlamp",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_floorlamp2","inh",6,"A3PL_Winchester_Floorlamp2",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_floorlamp3","inh",6,"A3PL_Winchester_Floorlamp3",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_wardrobe","inh",6,"A3PL_Winchester_Wardrobe",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_drawers","inh",6,"A3PL_Winchester_Drawers",0,true,true,true,false,false,"", [0,0,0], ""],
	["furn_winchester_wine","inh",6,"A3PL_Winchester_WineBottles",0,true,true,true,false,false,"", [0,0,0], ""],
	["cash",localize"STR_ConfigItems_cash", 0.0005, "A3PL_Money", 0, true, true, true, true, true, "", [0,0,0], ""],
	["apple",localize"STR_ConfigItems_apple", 1, "A3PL_Apple", 0, true, true, true, true, true, "A3PL_Items_Food", [0,0,0], ""],
	["handcuffs",localize"STR_ConfigItems_handcuffs", 1, "A3PL_Handcuffs", 0, true, true, true, true, true, "", [0,0,0], ""],
	["Lifebuoy",localize"STR_ConfigItems_Lifebuoy", 1, "A3PL_Lifebuoy", 0, true, true, true, true, true, "", [0,0,0], ""],
	["doorkey",localize"STR_ConfigItems_doorkey", 0.1, "A3PL_HouseKey",0,true,true,true, true, true,"", [0,0,0], ""],
	["lamington",localize"STR_ConfigItems_lamington", 0.1, "A3PL_Lamington",0,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["sausages",localize"STR_ConfigItems_sausages", 0.1, "A3PL_Sausages",0,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["meatpie",localize"STR_ConfigItems_meatpie", 0.5, "A3PL_MeatPie",0,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["meat_goat",localize"STR_ConfigItems_meat_goat",0.5,"A3PL_Steak",90,true,true,true,true,true,"", [0,0,0], ""],
	["meat_cow",localize"STR_ConfigItems_meat_cow",0.5,"A3PL_Steak",90,true,true,true,true,true,"", [0,0,0], ""],
	["meat_sheep",localize"STR_ConfigItems_meat_sheep",0.5,"A3PL_Steak",90,true,true,true,true,true,"", [0,0,0], ""],
	["meat_boar",localize"STR_ConfigItems_meat_boar",0.5,"A3PL_Steak",90,true,true,true,true,true,"", [0,0,0], ""],
	["meat_goat_tag",localize"STR_ConfigItems_meat_goat_tag",0.5,"A3PL_Steak",90,true,true,true,true,true,"", [0,0,0], ""],
	["meat_cow_tag",localize"STR_ConfigItems_meat_cow_tag",0.5,"A3PL_Steak",90,true,true,true,true,true,"", [0,0,0], ""],
	["meat_sheep_tag",localize"STR_ConfigItems_meat_sheep_tag",0.5,"A3PL_Steak",90,true,true,true,true,true,"", [0,0,0], ""],
	["meat_boar_tag",localize"STR_ConfigItems_meat_boar_tag",0.5,"A3PL_Steak",90,true,true,true,true,true,"", [0,0,0], ""],

	["tag_meat",localize"STR_ConfigItems_tag_meat",0.1,"A3PL_File2",0,true,true,true, true, true,"", [0,0,0], ""],
	["tag_shark",localize"STR_ConfigItems_tag_shark",0.1,"A3PL_File2",0,true,true,true, true, true,"", [0,0,0], ""],
	["tag_fish",localize"STR_ConfigItems_tag_fish",0.1,"A3PL_File2",0,true,true,true, true, true,"", [0,0,0], ""],

	["mullet",localize"STR_ConfigItems_mullet",0.5,"A3PL_Mullet",90,true,true,true,true,true,"", [0,0,0], ""],
	["mullet_tag",localize"STR_ConfigItems_mullet_tag",0.5,"A3PL_Mullet",90,true,true,true,true,true,"", [0,0,0], ""],
	["shark_2lb",localize"STR_ConfigItems_shark_2lb",2,"A3PL_CatShark",90,true,true,true,true,true,"", [0,0,0], ""],
	["shark_2lb_tag",localize"STR_ConfigItems_shark_2lb_tag",2,"A3PL_CatShark",90,true,true,true,true,true,"", [0,0,0], ""],
	["shark_4lb",localize"STR_ConfigItems_shark_4lb",4,"A3PL_CatShark",90,true,true,true,true,true,"", [0,0,0], ""],
	["shark_4lb_tag",localize"STR_ConfigItems_shark_4lb_tag",4,"A3PL_CatShark",90,true,true,true,true,true,"", [0,0,0], ""],
	["shark_5lb",localize"STR_ConfigItems_shark_5lb",5,"A3PL_CatShark",90,true,true,true,true,true,"", [0,0,0], ""],
	["shark_5lb_tag",localize"STR_ConfigItems_shark_5lb_tag",5,"A3PL_CatShark",90,true,true,true,true,true,"", [0,0,0], ""],
	["shark_7lb",localize"STR_ConfigItems_shark_7lb",7,"A3PL_CatShark",90,true,true,true,true,true,"", [0,0,0], ""],
	["shark_7lb_tag",localize"STR_ConfigItems_shark_7lb_tag",7,"A3PL_CatShark",90,true,true,true,true,true,"", [0,0,0], ""],
	["shark_10lb",localize"STR_ConfigItems_shark_10lb",10,"A3PL_CatShark",90,true,true,true,true,true,"", [0,0,0], ""],
	["shark_10lb_tag",localize"STR_ConfigItems_shark_10lb_tag",10,"A3PL_CatShark",90,true,true,true,true,true,"", [0,0,0], ""],
	["turtle",localize"STR_ConfigItems_turtle",2,"A3PL_Ornate",90,true,true,true,true,true,"", [0,0,0], ""],

	["Meat_Scraps",localize"STR_ConfigItems_Meat_Scraps",0.5,"A3PL_Burger_Raw",90,true,true,true,true,true,"", [0,0,0], ""],
	["burger_bun",localize"STR_ConfigItems_burger_bun",0.5,"A3PL_Burger_Bun",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["burger_burnt",localize"STR_ConfigItems_burger_burnt",0.5,"A3PL_Burger_Burnt",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["burger_raw",localize"STR_ConfigItems_burger_raw",0.5,"A3PL_Burger_Raw",90,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["burger_cooked",localize"STR_ConfigItems_burger_cooked",0.5,"A3PL_Burger_Cooked",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["burger_full_raw",localize"STR_ConfigItems_burger_full_raw",1,"A3PL_Burger_Full",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["burger_full_cooked",localize"STR_ConfigItems_burger_full_cooked",1,"A3PL_Burger_Full",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["burger_full_burnt",localize"STR_ConfigItems_burger_full_burnt",1,"A3PL_Burger_Full",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["net",localize"STR_ConfigItems_net",1,"A3PL_FishingBuoy",0,true,true,true, true, true,"", [0,0,0], ""],
	["bucket_empty",localize"STR_ConfigItems_bucket_empty",1,"A3PL_Bucket",0,true,true,true, true, true,"", [0,0,0], ""],
	["bucket_full",localize"STR_ConfigItems_bucket_full",1,"A3PL_BucketFull",0,true,true,true, true, true,"", [0,0,0], ""],
	["repairwrench",localize"STR_ConfigItems_repairwrench",3,"A3PL_Wrench",0,true,true,true, true, true,"", [0,0,0], ""],
	["ticket",localize"STR_ConfigItems_ticket",0.1,"A3PL_Ticket",0,false,false,true, true, true,"", [0,0,0], ""],
	["Ladder",localize"STR_ConfigItems_Ladder",5,"A3PL_Ladder",0,true,true,true,false,false,"", [0,0,0], ""],
	["drill_bit",localize"STR_ConfigItems_drill_bit", 3, "A3PL_Drill_Bit",0,true,true,true,true,true,"", [0,0,0], ""],
	["stinger",localize"STR_ConfigItems_stinger", 3, "A3PL_Stinger",0,true,true,true,true,true,"", [2,0.5,0], ""],
	["seed_wheat",localize"STR_ConfigItems_seed_wheat",0.5,"A3PL_Seed_Wheat",0,true,true,true, true, true,"", [0,0,0], ""],
	["seed_corn",localize"STR_ConfigItems_seed_corn",0.5,"A3PL_Seed_Corn",0,true,true,true, true, true,"", [0,0,0], ""],
	["seed_marijuana",localize"STR_ConfigItems_seed_marijuana",0.5,"A3PL_Seed_Marijuana",0,true,true,true, true, true,"", [0,0,0], ""],
	["seed_lettuce",localize"STR_ConfigItems_seed_lettuce",0.5,"A3PL_Seed_Lettuce",0,true,true,true, true, true,"", [0,0,0], ""],

	["corn",localize"STR_ConfigItems_corn",2,"A3PL_CornCob",0,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["lettuce",localize"STR_ConfigItems_lettuce",2,"A3PL_LettuceItem",0,true,true,true, true, true,"A3PL_Items_Food", [0,0,0], ""],
	["beer",localize"STR_ConfigItems_beer", 0.1, "A3PL_Corona",20,true,true,true,true,true,"A3PL_Items_Thirst", [-0.03,-0.05,0.1], ""],
	["beer_gold",localize"STR_ConfigItems_beer_gold", 0.1, "A3PL_4xGold",20,true,true,true,true,true,"A3PL_Items_Thirst", [0,0,0], ""],
	["cocaine",localize"STR_ConfigItems_cocaine", 1, "A3PL_PowderedMilk",15,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["shrooms",localize"STR_ConfigItems_shrooms", 0.5, "A3FL_Mushroom",15,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["popcornbucket",localize"STR_ConfigItems_popcornbucket",0.5,"A3PL_PopcornBucket",0,false,true,true,true,true,"", [0,0,0], ""],
	["Camper_Light",localize"STR_ConfigItems_Camper_Light",5,"A3PL_Camping_Light",0,true,true,true,true,true,"", [0,0,0], ""],
	["Salad",localize"STR_ConfigItems_Salad",0.5,"A3PL_Salad",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["tacoshell",localize"STR_ConfigItems_tacoshell",0.5,"A3PL_TacoShell",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["taco_raw",localize"STR_ConfigItems_taco_raw",1,"A3PL_Taco",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["taco_cooked",localize"STR_ConfigItems_taco_cooked",1,"A3PL_Taco",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["taco_burned",localize"STR_ConfigItems_taco_burned",1,"A3PL_Taco",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["fish_raw",localize"STR_ConfigItems_fish_raw",1,"A3PL_Fish_Raw",0.5,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["fish_cooked",localize"STR_ConfigItems_fish_cooked",0.5,"A3PL_Fish_Cooked",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["fish_burned",localize"STR_ConfigItems_fish_burned",0.5,"A3PL_Fish_Burned",0,true,true,true,true,true,"A3PL_Items_Food", [0,0,0], ""],
	["rocket_blue",localize"STR_ConfigItems_rocket_blue",2,"A3PL_Rocket",0,true,true,true, true, true,"", [0,0,0], ""],
	["rocket_red",localize"STR_ConfigItems_rocket_red",2,"A3PL_Rocket",0,true,true,true, true, true,"", [0,0,0], ""],
	["rocket_green",localize"STR_ConfigItems_rocket_green",2,"A3PL_Rocket",0,true,true,true, true, true,"", [0,0,0], ""],
	["rocket_yellow",localize"STR_ConfigItems_rocket_yellow",2,"A3PL_Rocket",0,true,true,true, true, true,"", [0,0,0], ""],
	["FD_yAdapter",localize"STR_ConfigItems_FD_yAdapter",1,"A3PL_FD_yAdapter",0,true,true,true, true, true,"", [0,0,0], ""],
	["FD_Adapter",localize"STR_ConfigItems_FD_Adapter",1,"A3PL_FD_HoseEnd_Player",0,true,true,true, true, true,"", [0,0,0], ""],
	["FD_Hose",localize"STR_ConfigItems_FD_Hose",4,"A3PL_FD_HoseRolled",90,true,true,true,true,true,"", [0,0,0], ""],
	["FD_HydrantWrench",localize"STR_ConfigItems_FD_HydrantWrench",3,"A3PL_FD_HydrantWrench",0,true,true,true, true, true,"", [0,0,0], ""],
	["FD_Mask",localize"STR_ConfigItems_FD_Mask",6,"A3PL_FD_Mask_Obj",180,true,true,true, true, true,"", [-0.12,-0.15,-0.73], ""],
	["Pumpjack",localize"STR_ConfigItems_Pumpjack",50,"A3PL_Pumpjack",0,true,true,true,false,false,"", [0,0,0], ""],
	["mail",localize"STR_ConfigItems_mail",0.2,"A3PL_DeliveryBox",0,true,true,true,false,false,"", [0,0,0], ""],
	["Synthetic_Fibre",localize"STR_ConfigItems_Synthetic_Fibre",0.2,"A3PL_Synthetic_Fiber",0,true,true,true,true,true,"", [0,0,0], ""],
	["Nylon",localize"STR_ConfigItems_Nylon",0.2,"A3PL_Nylon",0,true,true,true,false,false,"", [0,0,0], ""],
	["Spandex",localize"STR_ConfigItems_Spandex",0.2,"A3PL_Spandex",0,true,true,true,false,false,"", [0,0,0], ""],
	["Polyester",localize"STR_ConfigItems_Polyester",1,"A3PL_Polyester",0,true,true,true,true,true,"", [0,0,0], ""],
	["Acrylic",localize"STR_ConfigItems_Acrylic",0.2,"A3PL_Acrylic",0,true,true,true,true,true,"", [0,0,0], ""],
	["Rayon",localize"STR_ConfigItems_Rayon",0.2,"A3PL_Rayon",0,true,true,true,false,false,"", [0,0,0], ""],
	["Aramid",localize"STR_ConfigItems_Aramid",1,"A3PL_Aramid",0,true,true,true,false,false,"", [0,0,0], ""],
	["Rubber",localize"STR_ConfigItems_Rubber",0.2,"A3PL_Rubber",0,true,true,true,true,true,"", [0,0,0], ""],
	["Crude_Oil",localize"STR_ConfigItems_Crude_Oil",367,"A3PL_OilBarrel",0,true,true,true,false,false,"", [0,0,0], ""],
	["LPG",localize"STR_ConfigItems_LPG",88,"A3PL_LPG",0,true,true,true,false,false,"", [0,0,0], ""],
	["Petrol",localize"STR_ConfigItems_Petrol",367,"A3PL_OilBarrel",0,true,true,true,false,false,"", [0,0,0], ""],
	["Kerosene",localize"STR_ConfigItems_Kerosene",367,"A3PL_Kerosene",0,true,true,true,false,false,"", [0,0,0], ""],
	["CanisterOil",localize"STR_ConfigItems_CanisterOil",4,"A3PL_CanisterOil",0,true,true,true,true,true,"", [0,0,0], ""],
	["Sand",localize"STR_ConfigItems_Sand",1,"A3PL_BucketSand",0,true,true,true,true,true,"", [0,0,0], ""],
	["Titanium_Ore",localize"STR_ConfigItems_Titanium_Ore",5,"A3PL_Titanium_Ore",0,true,true,true,true,true,"", [0,0,0], ""],
	["Titanium_Ingot",localize"STR_ConfigItems_Titanium_Ingot",3,"A3PL_Titanium_Ingot",0,true,true,true,true,true,"", [0,0,0], ""],
	["Aluminium_Ore",localize"STR_ConfigItems_Aluminium_Ore",1,"A3PL_Resource_Ore_Orange_Small",0,true,true,true,true,true,"", [0,0,0], ""],
	["Aluminium_Ingot",localize"STR_ConfigItems_Aluminium_Ingot",1,"A3PL_Aluminium_Ingot",0,true,true,true,true,true,"", [0,0,0], ""],
	["Aluminium",localize"STR_ConfigItems_Aluminium",1,"A3PL_Aluminium",0,true,true,true,true,true,"", [0,0,0], ""],
	["Iron_Ore",localize"STR_ConfigItems_Iron_Ore",1,"A3PL_Resource_Ore_Pink_Small",0,true,true,true,true,true,"", [0,0,0], ""],
	["Iron_Ingot",localize"STR_ConfigItems_Iron_Ingot",1,"A3PL_Iron_Ingot",0,true,true,true,true,true,"", [0,0,0], ""],
	["Coal_Ore",localize"STR_ConfigItems_Coal_Ore",1,"A3PL_Resource_Ore_Black_Small",0,true,true,true,true,true,"", [0,0,0], ""],
	["Coal_Ingot",localize"STR_ConfigItems_Coal_Ingot",1,"A3PL_Coal_Ingot",0,true,true,true,true,true,"", [0,0,0], ""],
	["Sulphur_Ore",localize"STR_ConfigItems_Sulphur_Ore",1,"A3PL_Resource_Ore_Yellow_Small",0,true,true,true,true,true,"", [0,0,0], ""],
	["Sulphur_Powder",localize"STR_ConfigItems_Sulphur_Powder",1,"A3PL_SulphurPowder",0,true,true,true,true,true,"", [0,0,0], ""],
	["Gunpowder",localize"STR_ConfigItems_Gunpowder",1,"A3PL_Gunpowder",0,true,true,true,true,true,"", [0,0,0], ""],
	["Steel",localize"STR_ConfigItems_Steel",1,"A3PL_Steel",0,true,true,true,true,true,"", [0,0,0], ""],
	["Titanium",localize"STR_ConfigItems_Titanium",1,"A3PL_Titanium",0,true,true,true,true,true,"", [0,0,0], ""],
	["Glass_Fibre",localize"STR_ConfigItems_Glass_Fibre",1,"A3PL_Glass_Fibre",0,true,true,true,true,true,"", [0,0,0], ""],
	["Glass",localize"STR_ConfigItems_Glass",1,"A3PL_Glass",0,true,true,true,true,true,"", [0,0,0], ""],
	["Fibreglass",localize"STR_ConfigItems_Fibreglass",1,"A3PL_Fibreglass",0,true,true,true,true,true,"", [0,0,0], ""],
	["Plastic",localize"STR_ConfigItems_Plastic",1,"A3PL_Plastic",0,true,true,true,true,true,"", [0,0,0], ""],
	["Kevlar",localize"STR_ConfigItems_Kevlar",1,"A3PL_Kevlar",0,true,true,true,true,true,"", [0,0,0], ""],
	["Engine",localize"STR_ConfigItems_Engine",80,"A3PL_Engine",0,true,true,true,true,true,"", [0,0,0], ""],
	["Trans",localize"STR_ConfigItems_Trans",50,"A3PL_Transmission",0,true,true,true,true,true,"", [0,0,0], ""],
	["Radiator",localize"STR_ConfigItems_Radiator",30,"A3PL_Radiator",0,true,true,true,true,true,"", [0,0,0], ""],
	["BrakeRotors",localize"STR_ConfigItems_BrakeRotors",15,"A3PL_Brake_Rotor",0,true,true,true,true,true,"", [0,0,0], ""],
	["Diff",localize"STR_ConfigItems_Diff",15,"A3PL_Diff",0,true,true,true,true,true,"", [0,0,0], ""],
	["FuelTank",localize"STR_ConfigItems_FuelTank",15,"A3PL_Fuel_Tank",0,true,true,true,true,true,"", [0,0,0], ""],
	["Chassis",localize"STR_ConfigItems_Chassis",50,"A3PL_Chassis",0,true,true,true,true,true,"", [0,0,0], ""],
	["DriveShaft",localize"STR_ConfigItems_DriveShaft",15,"A3PL_Drive_Shaft",0,true,true,true,true,true,"", [0,0,0], ""],
	["Exhaust",localize"STR_ConfigItems_Exhaust",10,"A3PL_Exhaust",0,true,true,true,true,true,"", [0,0,0], ""],
	["Windows",localize"STR_ConfigItems_Windows",5,"A3PL_Glass",0,true,true,true,true,true,"", [0,0,0], ""],
	["HEEngine",localize"STR_ConfigItems_HEEngine",80,"A3PL_Engine",0,true,true,true,true,true,"", [0,0,0], ""],
	["HETrans",localize"STR_ConfigItems_HETrans",50,"A3PL_Transmission",0,true,true,true,true,true,"", [0,0,0], ""],
	["HERadiator",localize"STR_ConfigItems_HERadiator",30,"A3PL_Radiator",0,true,true,true,true,true,"", [0,0,0], ""],
	["HEBrakeRotors",localize"STR_ConfigItems_HEBrakeRotors",15,"A3PL_Brake_Rotor",0,true,true,true,true,true,"", [0,0,0], ""],
	["HEDiff",localize"STR_ConfigItems_HEDiff",15,"A3PL_Diff",0,true,true,true,true,true,"", [0,0,0], ""],
	["HEFuelTank",localize"STR_ConfigItems_HEFuelTank",15,"A3PL_Fuel_Tank",0,true,true,true,true,true,"", [0,0,0], ""],
	["HEChassis",localize"STR_ConfigItems_HEChassis",50,"A3PL_Chassis",0,true,true,true,true,true,"", [0,0,0], ""],
	["HEDriveShaft",localize"STR_ConfigItems_HEDriveShaft",15,"A3PL_Drive_Shaft",0,true,true,true,true,true,"", [0,0,0], ""],
	["HEExhaust",localize"STR_ConfigItems_HEExhaust",10,"A3PL_Exhaust",0,true,true,true,true,true,"", [0,0,0], ""],
	["4WDDiff",localize"STR_ConfigItems_4WDDiff",15,"A3PL_Diff",0,true,true,true,true,true,"", [0,0,0], ""],
	["SteelRims",localize"STR_ConfigItems_SteelRims",10,"A3PL_SteelRims",0,true,true,true,true,true,"", [0,0,0], ""],
	["AlloyRims",localize"STR_ConfigItems_AlloyRims",10,"A3PL_AlloyRims",0,true,true,true,true,true,"", [0,0,0], ""],
	["Tyres",localize"STR_ConfigItems_Tyres",10,"A3PL_Tyre",0,true,true,true,true,true,"", [0,0,0], ""],

	["ME_Bucket",localize"STR_ConfigItems_ME_Bucket",0,"A3PL_MiniExcavator_Bucket",0,true,true,true,true,true,"", [0,0,0], localize"STR_ConfigItems_ExtractMineralsFromTheSoil"],
	["ME_Jackhammer",localize"STR_ConfigItems_ME_Jackhammer",0,"A3PL_MiniExcavator_Jackhammer",0,true,true,true,true,true,"", [0,0,0], localize"STR_ConfigItems_AllowsToSprayMinerals"],

	["Iron_Ingot_Pellet",localize"STR_ConfigItems_Iron_Ingot_Pellet",6,"A3PL_Iron_Ingot_Pellet",0,true,true,true,false,false,"", [0,0,0], ""],
	["Coal_Ingot_Pellet",localize"STR_ConfigItems_Coal_Ingot_Pellet",6,"A3PL_Coal_Ingot_Pellet",0,true,true,true,false,false,"", [0,0,0], ""],
	["Aluminium_Ingot_Pellet",localize"STR_ConfigItems_Aluminium_Ingot_Pellet",6,"A3PL_Aluminium_Ingot_Pellet",0,true,true,true,false,false,"", [0,0,0], ""],
	["Titanium_Ingot_Pellet",localize"STR_ConfigItems_Titanium_Ingot_Pellet",6,"A3PL_Titanium_Ingot_Pellet",0,true,true,true,false,false,"", [0,0,0], ""],
	["Steel_Pellet",localize"STR_ConfigItems_Steel_Pellet",6,"A3PL_Steel_Pellet",0,true,true,true,false,false,"", [0,0,0], ""],
	["Aluminium_Pellet",localize"STR_ConfigItems_AluminumPallet",6,"A3PL_Aluminium_Pellet",0,true,true,true,false,false,"", [0,0,0], ""],
	["Titanium_Pellet",localize"STR_ConfigItems_TitaniumPallet",6,"A3PL_Titanium_Pellet",0,true,true,true,false,false,"", [0,0,0], ""],

	["med_cast",localize"STR_ConfigItems_med_cast",0.1,"A3PL_Medical_Cast",0.05,true,true,true,true,true,"", [0,0,0], ""],
	["med_endotracheal",localize"STR_ConfigItems_med_endotracheal",0.025,"A3PL_Medical_Endotracheal",0,true,true,true,true,true,"", [0,0,0], ""],
	["med_icepack",localize"STR_ConfigItems_med_icepack",0.05,"A3PL_Medical_Icepack",0,true,true,true,true,true,"", [0,0,0], ""],
	["med_bandage",localize"STR_ConfigItems_med_bandage",0.05,"A3PL_Bandage",0,true,true,true,true,true,"", [0,0,0], ""],
	["med_kit",localize"STR_ConfigItems_med_kit",0.5,"A3PL_Medical_Kit",0,true,true,true,true,true,"", [0,0,0], ""],
	["med_oxygenmask",localize"STR_ConfigItems_med_oxygenmask",0.05,"A3PL_Medical_OxygenMask",0,true,true,true,true,true,"", [0,0,0], ""],
	["med_splint",localize"STR_ConfigItems_med_splint",0.025,"A3PL_Medical_Splint",0,true,true,true,true,true,"", [0,0,0], ""],
	["med_painkillers",localize"STR_ConfigItems_med_painkillers",0.05,"A3PL_PainKillers",0,true,true,true,true,true,"", [0,0,0], ""],
	["med_narcan",localize"STR_ConfigItems_med_narcan",0.05,"A3PL_PainKillers",0,true,true,true,true,true,"", [0,0,0], ""],
	["med_autograft",localize"STR_ConfigItems_med_autograft",0.5,"A3PL_Medical_Kit",0,true,true,true,true,true,"", [0,0,0], ""],
	["medS_bloodbag",localize"STR_ConfigItems_medS_bloodbag",0.05,"A3PL_BloodBag",0,true,true,true,true,true,"", [0,0,0], ""],

	["Blueprint_SMG",localize"STR_ConfigItems_Blueprint_SMG",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
	["Blueprint_Attachment",localize"STR_ConfigItems_Blueprint_Attachment",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
	["Blueprint_Pistol_Legal",localize"STR_ConfigItems_Blueprint_Pistol_Legal",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
	["Blueprint_Pistol_Legal_Ammo",localize"STR_ConfigItems_Blueprint_Pistol_Legal_Ammo",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],

	["Blueprint_balaclava",localize"STR_ConfigItems_Blueprint_Balaclava",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
	["Blueprint_Bandanna",localize"STR_ConfigItems_Blueprint_Bandanna",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
	["Blueprint_Shemag",localize"STR_ConfigItems_Blueprint_Shemag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],

	["Blueprint_A3PL_Taser",localize"STR_ConfigItems_Blueprint_A3PL_Taser",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_P07",localize"STR_ConfigItems_Blueprint_P07",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_P07_khk",localize"STR_ConfigItems_Blueprint_P07_khk",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_Pistol_heavy_01",localize"STR_ConfigItems_Blueprint_Pistol_heavy_01",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_ACPC2",localize"STR_ConfigItems_Blueprint_ACPC2",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_Pistol_01",localize"STR_ConfigItems_Blueprint_Pistol_01",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_Rook40",localize"STR_ConfigItems_Blueprint_Rook40",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_Pistol_heavy_02",localize"STR_ConfigItems_Blueprint_Pistol_heavy_02",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_hgun_Glock17",localize"STR_ConfigItems_Blueprint_hgun_Glock17",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_P226",localize"STR_ConfigItems_Blueprint_P226",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_SMG_05",localize"STR_ConfigItems_Blueprint_SMG_05",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
	["Blueprint_A3PL_TaserMag",localize"STR_ConfigItems_Blueprint_A3PL_TaserMag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_16Rnd_9x21_Mag",localize"STR_ConfigItems_Blueprint_16Rnd_9x21_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_11Rnd_45ACP_Mag",localize"STR_ConfigItems_Blueprint_11Rnd_45ACP_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_6Rnd_GreenSignal_F",localize"STR_ConfigItems_Blueprint_6Rnd_GreenSignal_F",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_6Rnd_RedSignal_F",localize"STR_ConfigItems_Blueprint_6Rnd_RedSignal_F",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_hgun_Pistol_Signal_F",localize"STR_ConfigItems_Blueprint_hgun_Pistol_Signal_F",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_6Rnd_45ACP_Mag",localize"STR_ConfigItems_Blueprint_6Rnd_45ACP_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_9Rnd_45ACP_Mag",localize"STR_ConfigItems_Blueprint_9Rnd_45ACP_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_10Rnd_9x21_Mag",localize"STR_ConfigItems_Blueprint_10Rnd_9x21_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_16Rnd_9x21_green_Mag",localize"STR_ConfigItems_Blueprint_16Rnd_9x21_green_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_16Rnd_9x21_yellow_Mag",localize"STR_ConfigItems_Blueprint_16Rnd_9x21_yellow_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_30Rnd_9x21_Mag",localize"STR_ConfigItems_Blueprint_30Rnd_9x21_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_A3PL_Red_Glock",localize"STR_ConfigItems_Blueprint_A3PL_Red_Glock",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_A3PL_Red_Glock_Mag",localize"STR_ConfigItems_Blueprint_A3PL_Red_Glock_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_A3PL_P226",localize"STR_ConfigItems_Blueprint_A3PL_P226",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_A3PL_P226_Mag",localize"STR_ConfigItems_Blueprint_A3PL_P226_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_30Rnd_9x21_Mag_SMG_02",localize"STR_ConfigItems_Blueprint_30Rnd_9x21_Mag_SMG_02",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_30Rnd_9x21_Green_Mag",localize"STR_ConfigItems_Blueprint_30Rnd_9x21_Green_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_30Rnd_9x21_Yellow_Mag",localize"STR_ConfigItems_Blueprint_30Rnd_9x21_Yellow_Mag",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],

    ["Blueprint_ACO",localize"STR_ConfigItems_Blueprint_ACO",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_Rangemaster_belt",localize"STR_ConfigItems_Blueprint_Rangemaster_belt",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
	["Blueprint_Rangemaster_belt_blk",localize"STR_ConfigItems_Blueprint_Rangemaster_belt_blk",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_ACO_red",localize"STR_ConfigItems_Blueprint_ACO_red",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_ACO_grn_smg",localize"STR_ConfigItems_Blueprint_ACO_grn_smg",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_flashlight",localize"STR_ConfigItems_Blueprint_flashlight",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],

    ["Blueprint_f450",localize"STR_ConfigItems_Blueprint_f450",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_e350",localize"STR_ConfigItems_Blueprint_e350",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_tahoe_FD",localize"STR_ConfigItems_Blueprint_tahoe_FD",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_ladder",localize"STR_ConfigItems_Blueprint_ladder",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_hladder",localize"STR_ConfigItems_Blueprint_hladder",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_pumper",localize"STR_ConfigItems_Blueprint_pumper",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_rescue",localize"STR_ConfigItems_Blueprint_rescue",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_cvpi_PD",localize"STR_ConfigItems_Blueprint_cvpi_PD",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_cvpi_PDST",localize"STR_ConfigItems_Blueprint_cvpi_PDST",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_tahoe_PD",localize"STR_ConfigItems_Blueprint_tahoe_PD",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_tahoe_PDST",localize"STR_ConfigItems_Blueprint_tahoe_PDST",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_mustang_PD",localize"STR_ConfigItems_Blueprint_mustang_PD",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_mustang_PDST",localize"STR_ConfigItems_Blueprint_mustang_PDST",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_charger_PD",localize"STR_ConfigItems_Blueprint_charger_PD",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_charger_PDST",localize"STR_ConfigItems_Blueprint_charger_PDST",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_silverado_PD",localize"STR_ConfigItems_Blueprint_silverado_PD",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_vettrz1_PD",localize"STR_ConfigItems_Blueprint_vettrz1_PD",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_Medium01_Medic",localize"STR_ConfigItems_Blueprint_Medium01_Medic",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_Boat_Civil_01_rescue",localize"STR_ConfigItems_Blueprint_Boat_Civil_01_rescue",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_RBM",localize"STR_ConfigItems_Blueprint_RBM",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_RHIB",localize"STR_ConfigItems_Blueprint_RHIB",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
	["Blueprint_Goose",localize"STR_ConfigItems_Blueprint_Goose",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_Jayhawk",localize"STR_ConfigItems_Blueprint_Jayhawk",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["Blueprint_MediumUSCG",localize"STR_ConfigItems_Blueprint_MediumUSCG",0,"A3PL_File2",0,true,true,true,true,true,"", [0,0,0], ""],
    ["furn_fridge",localize"STR_ConfigItems_Fridge", 15, "A3PL_Fridge",0,true,true,true,false,false,"", [0,0,0], ""],
    ["gift",localize"STR_ConfigItems_gift", 0.1, "A3PL_hw_candybucket",0,true,true,true,true,true,"", [0,0,0], ""],

    ["breathalizer",localize"STR_ConfigItems_breathalizer", 0.1, "A3PL_Breathalizer",0,true,true,true,true,true,"", [0,0,0], ""],
	["drug_kit",localize"STR_ConfigItems_drug_kit", 0.1, "A3PL_DrugTestingKit",0,true,true,true,true,true,"", [0,0,0], ""],

    ["sulphuric_acid",localize"STR_ConfigItems_sulphuric_acid", 0.1, "A3FL_SulphuricAcid",0,true,true,true,true,true,"", [0,0,0], ""],
    ["calcium_carbonate",localize"STR_ConfigItems_calcium_carbonate", 0.1, "A3FL_CalciumCarbonate",0,true,true,true,true,true,"", [0,0,0], ""],
    ["coca_paste",localize"STR_ConfigItems_coca_paste", 0.1, "A3FL_CocaPaste",0,true,true,true,true,true,"", [0,0,0], ""],
    ["potassium_permangate",localize"STR_ConfigItems_potassium_permangate", 0.1, "A3FL_Potassium",0,true,true,true,true,true,"", [0,0,0], ""],
    ["cocaine_base",localize"STR_ConfigItems_cocaine_base", 0.1, "A3FL_CocainePaste",0,true,true,true,true,true,"", [0,0,0], ""],
    ["ammonium_hydroxide",localize"STR_ConfigItems_ammonium_hydroxide", 0.1, "A3FL_Ammonium",0,true,true,true,true,true,"", [0,0,0], ""],
    ["acetone",localize"STR_ConfigItems_acetone", 0.1, "A3FL_Acetone",0,true,true,true,true,true,"", [0,0,0], ""],
    ["hydrocloric_acid",localize"STR_ConfigItems_hydrocloric_acid", 0.1, "A3FL_HydroAcid",0,true,true,true,true,true,"", [0,0,0], ""],
	["cocaine_barrel",localize"STR_ConfigItems_PlasticBarrel", 15, "A3FL_PlasticBarrel",0,true,true,true,false,false,"", [0,0,0], ""],
	["kerosene_jerrycan",localize"STR_ConfigItems_KeroJerry",30,"A3PL_Jerrycan",-90,true,true,true,true,true,"", [0,0,0], ""],
	["cocaine_hydrochloride",localize"STR_ConfigItems_CocaineHydrochloride", 0.1, "A3PL_PowderedMilk",0,true,true,true,true,true,"", [0,0,0], ""],
	["cocaine_brick",localize"STR_ConfigItems_CocaineBrick", 15, "A3FL_DrugBag",0,true,true,true,false,false,"", [0,0,0], ""],

	["coffee",localize"STR_ConfigItems_Coffee", 0.1, "A3FL_Coffee",0,true,true,true,false,false,"A3PL_Items_Thirst", [0,0,0], ""],
	["donut",localize"STR_ConfigItems_Donut", 0.1, "A3FL_Donut",0,true,true,true,false,false,"A3PL_Items_Food", [0,0,0], ""]
];
publicVariable "Config_Items";
