/*
	ArmA 3 Fishers Life
	Code written by ArmA 3 Fishers Life Development Team
	@Copyright ArmA 3 Fishers Life (https://www.arma3fisherslife.net)
	YOU ARE NOT ALLOWED TO COPY OR DISTRIBUTE THE CONTENT OF THIS FILE WITHOUT AUTHOR AGREEMENT
	More informations : https://www.bistudio.com/community/game-content-usage-rules
*/

//["factory_ID","classname","type",time,[["required",3],["components",200]],output,xpGain,levelRequired,description]
Config_Factories =
[
	["Chemical Plant",[9983.55,8496.61,0],
		["f_Synthetic_Fiber","Synthetic_Fibre","item",15,[["Crude_Oil",1]],50,5,0,"Makes 50 Synthetic Fiber"],
		["f_Glass_Fiber","Glass_Fibre","item",15,[["Sand",1]],50,5,0,"Makes 50 Glass Fiber"],
		["f_Titanium_Ore","Titanium_Ore","item",5,[["Sand",2]],8,8,0,"Makes 8 Titanium Ore"],
		["f_Polyester","Polyester","item",15,[["Synthetic_Fibre",1]],1,1,0,"Makes 1 Polyester"],
		["f_Rubber","Rubber","item",15,[["Synthetic_Fibre",5]],1,1,0,"Makes 1 Rubber"],
		["f_Fibreglass","Fibreglass","item",15,[["Glass_Fibre",10]],1,1,0,"Makes 1 Fiberglass"],
		["f_Plastic","Plastic","item",5,[["Crude_Oil",1]],15,1,0,"Makes 15 Plastic"],
		["f_waterbottlempty","waterbottlempty","item",5,[["Plastic",1]],1,1,0,"Makes 1 Empty Water Bottle"],
		["f_Aluminium_Ingot","Aluminium_Ingot","item",4,[["Aluminium_Ore",2]],1,20,0,"Makes 1 Aluminum Ingot"],
		["f_Sulphur_Powder","Sulphur_Powder","item",5,[["Sulphur_Ore",5]],10,3,0,"Makes 10 Sulphur Powder"],
		["f_gunpowder","Gunpowder","item",5,[["Sulphur_Powder",5],["Coal_Ingot",1]],5,2,0,"Makes 5 Gunpowder"],
		["f_Glass","Glass","item",5,[["Glass_Fibre",5]],1,1,0,"Makes 1 Glass"],
		["f_Titanium_Ingot","Titanium_Ingot","item",10,[["Titanium_Ingot_Pellet",1]],256,20,0,"Makes 256 Titanium Ingots"],
		["f_Iron_Ingot","Iron_Ingot","item",10,[["Iron_Ingot_Pellet",1]],256,20,0,"Makes 256 Iron Ingots"],
		["f_Coal_Ingot","Coal_Ingot","item",10,[["Coal_Ingot_Pellet",1]],256,20,0,"Makes 256 Coal Ingots"],
		["f_Aluminium_IngotS","Aluminium_Ingot","item",90,[["Aluminium_Ingot_Pellet",1]],256,20,0,"Makes 256 Aluminum Ingots"],
		["f_Sapphire_Ingot","Sapphire_Ingot","item",10,[["Sapphire_Ingot_Pallet",1]],256,20,0,"Makes 256 Sapphire Ingots"],
		["f_Vivianite_Ingot","Vivianite_Ingot","item",10,[["Vivianite_Ingot_Pallet",1]],256,20,0,"Makes 256 Vivianite Ingots"],
		["f_Emerald_Ingot","Emerald_Ingot","item",10,[["Emerald_Ingot_Pallet",1]],256,20,0,"Makes 256 Emerald Ingots"],
		["f_Gold_Ingot","Gold_Ingot","item",10,[["Gold_Ingot_Pallet",1]],256,20,0,"Makes 256 Gold Ingots"],
		["f_Amethyst_Ingot","Amethyst_Ingot","item",10,[["Amethyst_Ingot_Pallet",1]],256,20,0,"Makes 256 Amethyst Ingots"]
	],

	["Steel Mill",[4410.48,6755.92,0.15],
		["f_ME_Bucket","ME_Bucket","item",15,[["Steel",15]],1,5,0,"Makes 1 Excavator Bucket"],
		["f_ME_Jackhammer","ME_Jackhammer","item",15,[["Steel",15]],1,5,0,"Makes 1 Excavator Jackhammer"],
		["f_Iron_Ingot","Iron_Ingot","item",3,[["Iron_Ore",4]],1,5,0,"Makes 1 Iron Ingot"],
		["f_Coal_Ingot","Coal_Ingot","item",3,[["Coal_Ore",4]],1,5,0,"Makes 1 Coal Ingot"],
		["f_Titanium_Ingot","Titanium_Ingot","item",4,[["Titanium_Ore",6]],1,5,0,"Makes 1 Titanium Ingot"],
		["f_Sapphire_Ingot","Sapphire_Ingot","item",3,[["Sapphire_Ore",4]],1,5,0,"Makes 1 Sapphire Ingot"],
		["f_Vivianite_Ingot","Vivianite_Ingot","item",3,[["Vivianite_Ore",4]],1,5,0,"Makes 1 Vivianite Ingot"],
		["f_Emerald_Ingot","Emerald_Ingot","item",3,[["Emerald_Ore",4]],1,5,0,"Makes 1 Emerald Ingot"],
		["f_Gold_Ingot","Gold_Ingot","item",3,[["Gold_Ore",4]],1,5,0,"Makes 1 Gold Ingot"],
		["f_Amethyst_Ingot","Amethyst_Ingot","item",3,[["Amethyst_Ore",4]],1,5,0,"Makes 1 Amethyst Ingot"],
		["f_Steel","Steel","item",5,[["Iron_Ingot",4],["Coal_Ingot",2]],30,10,0,"Makes 30 Steel Sheets"],
		["f_Aluminium","Aluminium","item",5,[["Aluminium_Ingot",4],["Iron_Ingot",2],["Coal_Ingot",6]],30,10,0,"Makes 30 Aluminum Sheets"],
		["f_Gold","Gold_Sheet","item",5,[["Gold_Ingot",30],["Coal_Ingot",2]],30,10,0,"Makes 30 Gold Sheets"],
		["f_Titanium","Titanium","item",5,[["Titanium_Ingot",4],["Coal_Ingot",2]],15,10,0,"Makes 15 Titanium Sheets"],
		["f_SteelS","Steel","item",5,[["Steel_Pellet",1]],60,10,0,"Makes 60 Steel Sheets"],
		["f_AluminiumS","Aluminium","item",5,[["Aluminium_Pellet",1]],60,10,0,"Makes 60 Aluminum Sheets"],
		["f_TitaniumS","Titanium","item",10,[["Titanium_Pellet",1]],60,10,0,"Makes 60 Titanium Sheets"],
		["f_Steel_Pellet","Steel_Pellet","item",10,[["Steel",60]],1,20,0,"Makes 1 Steel Pallet"],
		["f_Aluminium_Pellet","Aluminium_Pellet","item",10,[["Aluminium",60]],1,20,0,"Makes 1 Aluminum Pallet"],
		["f_Titanium_Pellet","Titanium_Pellet","item",10,[["Titanium",60]],1,20,0,"Makes 1 Titanium Pallet"],
		["f_Iron_Ingot_Pellet","Iron_Ingot_Pellet","item",20,[["Iron_Ingot",256]],1,20,0,"Makes 1 Iron Ingot Pallet"],
		["f_Coal_Ingot_Pellet","Coal_Ingot_Pellet","item",20,[["Coal_Ingot",256]],1,20,0,"Makes 1 Coal Ingot Pallet"],
		["f_Aluminium_Ingot_Pellet","Aluminium_Ingot_Pellet","item",20,[["Aluminium_Ingot",256]],1,20,0,"Makes 1 Aluminum Ingot Pallet"],
		["f_Titanium_Ingot_Pellet","Titanium_Ingot_Pellet","item",20,[["Titanium_Ingot",256]],1,20,0,"Makes 1 Titanium Ingot Pallet"],
		["f_Sapphire_Ingot_Pallet","Sapphire_Ingot_Pallet","item",20,[["Sapphire_Ingot",256]],1,20,0,"Makes 1 Sapphire Ingot Pallet"],
		["f_Vivianite_Ingot_Pallet","Vivianite_Ingot_Pallet","item",20,[["Vivianite_Ingot",256]],1,20,0,"Makes 1 Vivianite Ingot Pallet"],
		["f_Emerald_Ingot_Pallet","Emerald_Ingot_Pallet","item",20,[["Emerald_Ingot",256]],1,20,0,"Makes 1 Emerald Ingot Pallet"],
		["f_Gold_Ingot_Pallet","Gold_Ingot_Pallet","item",20,[["Gold_Ingot",256]],1,20,0,"Makes 1 Gold Ingot Pallet"],
		["f_Amethyst_Ingot_Pallet","Amethyst_Ingot_Pallet","item",20,[["Amethyst_Ingot",256]],1,20,0,"Makes 1 Amethyst Ingot Pallet"]
	],

	["Oil Refinery",[4409.1,6678.72,0.168],
		["f_pumpjack","Pumpjack","item",5,[["Steel_Pellet",3]],1,25,0,"Makes 1 Pumpjack; Used for Oil Drilling"],
		["f_Petrol","Petrol","item",5,[["Crude_Oil",1]],3,3,0,"Makes 3 Petrol"],
		["f_jerrycan_empty","jerrycan_empty","item",5,[["Steel",2]],2,4,0,"Makes 2 Empty Jerry Cans"],
		["f_jerrycan","jerrycan","item",5,[["Petrol",1],["Steel",2]],2,4,0,"Makes 2 Jerry Cans"],
		["f_jerrycan2","jerrycan","item",5,[["Petrol",1],["jerrycan_empty",2]],2,4,0,"Makes 2 Jerry Cans"],
		["f_jerrycan_kero","kerosene_jerrycan","item",5,[["Kerosene",1],["Steel",2]],2,4,0,"Makes 2 Kerosene Jerry Cans"],
		["f_jerrycan_kero2","kerosene_jerrycan","item",5,[["Kerosene",1],["jerrycan_empty",2]],2,4,0,"Makes 2 Kerosene Jerry Cans"],
		["f_Kerosene","Kerosene","item",10,[["Crude_Oil",1]],1,1,0,"Makes 1 Kerosene"],
		["f_CanisterOil","CanisterOil","item",5,[["Crude_Oil",1]],20,5,0,"Makes 20 Oil Canisters"]
	],

	["Goods Factory",[6540.34,6670.7,0.168],
		["f_repairwrench","repairwrench","item",8,[["Steel",15]],3,3,0,"Makes 3 Repair Wrenches"],
		["f_Rangefinder","Rangefinder","aitem",8,[["Steel",2],["Glass",2],["Plastic",5]],1,1,0,"Makes 1 RangeFinder"],
		["f_FD_Adapter","FD_Adapter","item",8,[["Steel",5]],5,5,0,"Makes 5 Hose Adapters"],
		["f_FD_Hose","FD_Hose","item",8,[["Rubber",1]],3,3,0,"Makes 3 Hoses"],
		["f_Net","net","item",8,[["Plastic",5]],10,10,0,"Makes 10 Fishing Nets"],
		["f_Bucket_Empty","bucket_empty","item",8,[["Plastic",1]],5,5,0,"Makes 5 Empty Buckets"],
		["f_Camper_Light","Camper_Light","item",8,[["Steel",5],["CanisterOil",5]],10,10,0,"Makes 10 Camper Lights"],
		["f_RocketB","rocket_blue","item",8,[["Plastic",3],["Gunpowder",2],["Sulphur_Powder",1]],3,3,0,"Makes 3 Blue Fireworks"],
		["f_RocketR","rocket_red","item",8,[["Plastic",3],["Gunpowder",2],["Sulphur_Powder",1]],3,3,0,"Makes 3 Red Fireworks"],
		["f_RocketG","rocket_green","item",8,[["Plastic",3],["Gunpowder",2],["Sulphur_Powder",1]],3,3,0,"Makes 3 Green Fireworks"],
		["f_RocketY","rocket_yellow","item",8,[["Plastic",3],["Gunpowder",2],["Sulphur_Powder",1]],3,3,0,"Makes 3 Yellow Fireworks"]
	],

	["Food Processing Plant",[8968.17,6391.78,0.168],
		["f_cola","coke","item",15,[["coca",2],["sugarcane",2],["Aluminium_Ingot",1]],6,3,0,"Makes 3 Soda; Replenishes 30% Thirst"],
		["f_Coffee_Cup_Large","coffee_cup_large","item",15,[["coca",6],["plastic",6]],4,5,0,"Makes 4 Large Coffee; Replenishes 50% Thirst"],
		["f_Coffee_Cup_Medium","coffee_cup_medium","item",15,[["coca",4],["plastic",4]],4,4,0,"Makes 4 Medium Coffee; Replenishes 40% Thirst"],
		["f_Coffee_Cup_Small","coffee_cup_small","item",15,[["coca",2],["plastic",2]],4,3,0,"Makes 4 Small Coffee; Replenishes 30% Thirst"],
		["f_popcornbucket","popcornbucket","item",15,[["Corn",1]],10,1,0,"Makes 10 Popcorn Buckets; Prevents Hunger Loss when held in hand"],
		["f_burgerbun","burger_bun","item",15,[["wheat",1]],10,1,0,"Makes 10 Burger Buns; Replenishes 8% Hunger"],
		["f_burger_raw","burger_raw","item",15,[["bucket_full",1]],10,1,0,"Makes 10 Raw Fish Burgers; Causes 6% Hunger Loss"],
		["f_tacoshell","tacoshell","item",15,[["Corn",1]],20,1,0,"Makes 20 Taco Shells; Replenishes 2% Hunger"],
		["f_salad","salad","item",15,[["Lettuce",1]],5,1,0,"Makes 5 Salad; Replenishes 5% Hunger"],
		["f_fish","fish_raw","item",15,[["bucket_full",1]],10,1,0,"Makes 10 Raw Fish; Causes 4% Hunger Loss"],
		["f_pizzabites","pizzabites","item",15,[["meat_boar_tag",3],["bread",1]],2,5,0,"Makes 2 Pizza Bites; Replenishes 25% Hunger"],
		["f_soupcoup","soupcup","item",15,[["meat_sheep_tag",1],["corn",5]],2,4,0,"Makes 2 Lamb Stew; Replenishes 20% Hunger"],
		["f_cookies","cookies","item",15,[["coca",2],["sugarcane",2],["wheat",15]],2,3,0,"Makes 2 Cookies; Replenishes 15% Hunger"],
		["f_cereal","cereal","item",15,[["corn",10],["wheat",20]],1,4,0,"Makes 1 Cereal; Replenishes 20% Hunger"],
		["f_bread","bread","item",15,[["wheat",30]],2,2,0,"Makes 2 Bread; Replenishes 10% Hunger"],
		["f_lamington","lamington","item",15,[["sugarcane",3],["bread",1]],2,3,0,"Makes 2 Lamington; Replenishes 15% Hunger"],
		["f_sausages","sausages","item",15,[["meat_boar",2]],2,5,0,"Makes 2 Sausages; Replenishes 30% Hunger"],
		["f_burger_full_cooked","burger_full_cooked","item",15,[["salad",1],["burger_bun",1],["burger_cooked",1]],2,10,0,"Makes 2 Cooked Fish Burgers; Replenishes 50% Hunger"],
		["f_taco_cooked","taco_cooked","item",15,[["salad",1],["tacoshell",1],["fish_cooked",1]],2,10,0,"Makes 2 Cooked Fish Tacos; Replenishes 50% Hunger"],
		["f_meatpie","meatpie","item",15,[["meat_sheep_tag",1],["meat_boar_tag",1],["meat_goat_tag",1],["bread",1]],2,20,0,"Makes 2 Meat Pies; Replenishes 100% Hunger"]
	],

	["Illegal Weapon Factory",[7653.55,8482.62,1.5],
		["f_P07","hgun_P07_F","weapon",120,[["Steel",100]],1,25,0,"Makes 1 P07 9mm Pistol"],
		["f_P07_khk","hgun_P07_khk_F","weapon",120,[["Steel",100]],1,25,0,"Makes 1 P07 Khaki 9mm Pistol"],
		["f_P07_blk","hgun_P07_blk_F","weapon",120,[["Steel",100]],1,25,0,"Makes 1 P07 Black 9mm Pistol"],
		["f_Pistol_heavy_01","hgun_Pistol_heavy_01_F","weapon",120,[["Steel",100]],1,25,0,"Makes 1 4-Five .45 ACP Pistol"],
		["f_ACPC2","hgun_ACPC2_F","weapon",120,[["Steel",100]],1,25,0,"Makes 1 ACP-C2 .45 ACP Pistol"],
		["f_Pistol_01","hgun_Pistol_01_F","weapon",120,[["Steel",100]],1,25,0,"Makes 1 PM 9mm Pistol"],
		["f_Rook40","hgun_Rook40_F","weapon",120,[["Steel",100]],1,25,0,"Makes 1 Rook-40 9mm Pistol"],
		["f_Pistol_heavy_02","hgun_Pistol_heavy_02_F","weapon",120,[["Steel",100]],1,25,0,"Makes 1 Zubr .45 ACP Pistol"],
		["f_Glock17","A3FL_Glock17","weapon",120,[["Steel",100]],1,0,0,"Makes 1 Glock 17 Pistol"],
		["f_Glock18","A3FL_Glock18","weapon",120,[["Steel",120]],1,0,0,"Makes 1 Glock 18 Pistol"],
		["f_P226","A3PL_P226","weapon",120,[["Steel",100]],1,25,0,"Makes 1 SIG P226 Pistol"],
		["f_P227","A3FL_P227","weapon",120,[["Steel",100]],1,25,0,"Makes 1 SIG P227 Pistol"],
		["f_Beretta92","A3FL_Beretta92","weapon",120,[["Steel",100]],1,25,0,"Makes 1 Beretta 92 Pistol"],
		["f_DesertEagle","A3FL_DesertEagle","weapon",120,[["Steel",150]],1,25,0,"Makes 1 Desert Eagle Pistol"],
		["f_SMG_01_F","SMG_01_F","weapon",300,[["Steel",1150]],1,75,0,"Makes 1 Vermin .45 ACP SMG"],
		["f_SMG_02_F","SMG_02_F","weapon",300,[["Steel",1150]],1,75,0,"Makes 1 Sting 9mm SMG"],
		["f_SMG_05_F","SMG_05_F","weapon",300,[["Steel",1150]],1,75,0,"Makes 1 Protector 9mm SMG"],
		["f_UMP","A3FL_UMP","weapon",300,[["Steel",1150]],1,75,0,"Makes 1 UMP 45 SMG"],
		["f_Vector","A3FL_Vector","weapon",300,[["Steel",1150]],1,75,0,"Makes 1 Kriss Vector SMG"],
		["f_Mossberg_590K","A3FL_Mossberg_590k","weapon",300,[["Steel",850]],1,100,0,"Makes 1 Mossberg 590k Shotgun"],
		["f_arifle_AKM_F","arifle_AKM_F","weapon",600,[["Steel",1650]],1,150,0,"Makes 1 AKM 7.62mm Rifle"],
		["f_m16","A3PL_M16","weapon",600,[["Steel",1650]],1,150,0,"Makes 1 M16A2 Rifle"],
		["f_16Rnd_9x21_Mag","16Rnd_9x21_Mag","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 9mm 16Rnd Mags; Used in P07/Rook-40"],
		["f_11Rnd_45ACP_Mag","11Rnd_45ACP_Mag","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 .45 ACP 11Rnd Mags; Used in 4-five ACP"],
		["f_6Rnd_45ACP_Mag","6Rnd_45ACP_Cylinder","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 .45 ACP 6Rnd Cylinders; Used in Zubr"],
		["f_9Rnd_45ACP_Mag","9Rnd_45ACP_Mag","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 .45 ACP 9Rnd Mags; Used in ACP-C2"],
		["f_10Rnd_9x21_Mag","10Rnd_9x21_Mag","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 9mm 10Rnd Mags; Used in PM"],
		["f_Glock17_Mag","A3FL_Glock17_Mag","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 9x19mm 17Rnd Mags; Used in Glock17"],
		["f_Glock18_Mag","A3FL_Glock18_Mag","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 9x19mm 17Rnd Mags; Used in Glock18"],
		["f_P226_Mag","A3PL_P226_Mag","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 9x19mm 15Rnd Mags; Used in SIG P226"],
		["f_P227_Mag","A3FL_P227_Mag","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 9x21mm 12Rnd .45 Mags; Used in SIG P227"],
		["f_Beretta92_Mag","A3FL_Beretta92_Mag","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 9x19mm 15Rnd Mags; Used in Beretta 92"],
		["f_DesertEagle_Mag","A3FL_DesertEagle_Mag","magazine",60,[["Steel",30],["Gunpowder",5]],5,10,0,"Makes 5 .50 7Rnd Mags; Used in Desert Eagle"],
		["f_30Rnd_45ACP_Mag_SMG_01","30Rnd_45ACP_Mag_SMG_01","magazine",60,[["Steel",35],["Gunpowder",5]],2,10,0,"Makes 2 .45 ACP 30Rnd Mags; Used in Vermin"],
		["f_30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","magazine",60,[["Steel",35],["Gunpowder",5]],2,10,0,"Makes 2 9mm 30Rnd Mags; Used in Sting/Protector"],
		["f_UMP_Mag","A3FL_UMP_Mag","magazine",60,[["Steel",35],["Gunpowder",5]],2,10,0,"Makes 2 .45 35Rnd Mags; Used in HK UMP"],
		["f_Vector_Mag","A3FL_Vector_Mag","magazine",60,[["Steel",35],["Gunpowder",5]],2,10,0,"Makes 2 .45 26Rnd Mags; Used in Kirss Vector"],
		["f_30Rnd_762x39_Mag_F","30Rnd_762x39_Mag_F","magazine",60,[["Steel",35],["Gunpowder",5]],2,10,0,"Makes 2 7.62mm 30Rnd Mags; Used in AKM"],
		["f_m16_mag","A3PL_M16_Mag","magazine",60,[["Steel",35],["Gunpowder",5]],2,10,0,"Makes 2 5.56x45mm 30Rnd Mags; Used in M16A2/Colt M4A1"],
		["f_Mossberg_590K_8Rnd_buck","A3FL_Mossberg_590k_8Rnd_buck","magazine",60,[["Steel",30],["Gunpowder",5]],2,10,0,"Makes 2 12 Guage 8Rnd Buckshot Mags; Used in Mossberg 590k"],
		["f_optic_Holosight_blk_F","optic_Holosight_blk_F","aitem",60,[["Steel",100]],1,25,0,"Makes 1 Mk17 Holosight; Used on all Rifles/SMGs"],
		["f_optic_ACO_grn","optic_ACO_grn","aitem",60,[["Steel",100]],1,25,0,"Makes 1 ACO Sight; Used on all SMGs"],
		["f_optic_ACO_grn_smg","optic_ACO_grn_smg","aitem",60,[["Steel",100]],1,25,0,"Makes 1 ACO Sight; Used on all SMGs"],
		["f_optic_Holosight_smg_blk_F","optic_Holosight_smg_blk_F","aitem",60,[["Steel",100]],1,25,0,"Makes 1 Mk17 Holosight; Used on all SMGs"],
		["f_optic_ACO_smg","optic_ACO_smg","aitem",60,[["Steel",100]],1,25,0,"Makes 1 ACO Sight; Used on all Rifles/SMGs"],
		["f_acc_flashlight_pistol","acc_flashlight_pistol","aitem",60,[["Steel",250]],1,25,0,"Makes 1 Pistol Flashlight; Used on most Pistols"],
		["f_acc_flashlight","acc_flashlight","aitem",60,[["Steel",250]],1,25,0,"Makes 1 SMG Flashlight; Used on most SMGs"]
	],

	["Marine Factory",[4898.23,5060.04,13],
		["f_Rebreather","V_RebreatherB","vest",5,[["Rubber",2],["Fibreglass",8],["Plastic",10]],1,10,0,""],
		["f_jetski","C_Scooter_Transport_01_F","car",10,[["Steel_Pellet",1]],1,10,0,""],
		["f_Motorboat","A3PL_Motorboat","car",120,[["Steel_Pellet",2]],1,20,0,""],
		["f_RHIB","A3PL_RHIB","car",240,[["Aluminium_Pellet",8]],1,25,0,""],
		["f_LCM","A3FL_LCM","car",300,[["Steel_Pellet",2],["Aluminium_Pellet",12]],1,25,0,""],
		["f_LuxuryYatch","A3PL_Yacht","car",1800,[["Aluminium_Pellet",100]],1,200,0,""]
	],

	["Aircraft Factory",[2907.86,5260.62,0.4],
		["f_Heli_Light","C_Heli_Light_01_civil_F","plane",1800,[["Aluminium_Pellet",50],["Steel_Pellet",50],["Titanium_Pellet",25],["Glass",10]],1,100,0,""],
		["f_Heli","Heli_Medium01_H","plane",1800,[["Aluminium_Pellet",100],["Glass",40],["Titanium_Pellet",20],["Fibreglass",40],["Steel_Pellet",75]],1,150,0,""],
		["f_Military_Heli","Heli_Medium01_Military_H","plane",1800,[["Aluminium_Pellet",100],["Glass",40],["Titanium_Pellet",20],["Fibreglass",40],["Steel_Pellet",75]],1,150,0,""],
		["f_Veteran_Heli","Heli_Medium01_Veteran_H","plane",1800,[["Aluminium_Pellet",100],["Glass",40],["Titanium_Pellet",20],["Fibreglass",40],["Steel_Pellet",75]],1,150,0,""],
		["f_Luxury_Heli","Heli_Medium01_Luxury_H","plane",1800,[["Aluminium_Pellet",100],["Glass",40],["Titanium_Pellet",20],["Fibreglass",40],["Steel_Pellet",75]],1,150,0,""],
		["f_Cessna172","A3PL_Cessna172","plane",1800,[["Aluminium_Pellet",30],["Steel_Pellet",25]],1,150,0,""],
		["f_Goose","A3PL_Goose_Base","plane",1800,[["Aluminium_Pellet",35],["Steel_Pellet",50]],1,150,0,""]
	],

	["Vehicle Factory",[3000.25,5352.92,0.4],
		["f_Windows","Windows","item",5,[["Glass",2]],4,2,0,""],
		["f_Tyres","Tyres","item",5,[["Rubber",4]],8,2,0,""],
		["f_C_Kart_01_F","C_Kart_01_F","car",300,[["Steel_Pellet",3]],1,30,0,""],
		["f_scooter","K_Scooter_DarkBlue","car",300,[["Steel_Pellet",3]],1,30,0,""],
		["f_quad","C_Quadbike_01_F","car",300,[["Steel_Pellet",3]],1,30,0,""],
		["f_CVPI_rust","A3PL_CVPI_Rusty","car",300,[["Steel_Pellet",3],["Windows",4]],1,30,0,""],
		["f_HondaCRX","A3PL_CRX","car",300,[["Steel_Pellet",6],["Aluminium_Pellet",2],["Windows",4],["Tyres",4]],1,30,0,""],
		["f_CVPI","A3PL_CVPI","car",300,[["Steel_Pellet",6],["Aluminium_Pellet",2],["Windows",2],["Tyres",4]],1,30,0,""],
		["f_CVPI_Taxi","A3PL_CVPI_Taxi","car",300,[["Steel_Pellet",6],["Aluminium_Pellet",2],["Windows",2],["Tyres",4]],1,30,0,""],
		["f_Ram","A3PL_Ram","car",600,[["Steel_Pellet",7],["Aluminium_Pellet",2],["Windows",2],["Tyres",4]],1,60,0,""],
		["f_150","A3PL_F150","car",600,[["Steel_Pellet",7],["Aluminium_Pellet",11],["Windows",2],["Tyres",4]],1,60,0,""],
		["f_Raptor","A3PL_Raptor","car",600,[["Steel_Pellet",7],["Aluminium_Pellet",11],["Windows",2],["Tyres",4]],1,60,0,""],
		["f_Explorer_Platinum_20","A3FL_Explorer_Platinum_20","car",1200,[["Steel_Pellet",20],["Aluminium_Pellet",25],["Titanium_Pellet",10],["Windows",4],["Tyres",4]],1,120,0,""],
		["f_Silverado","A3PL_Silverado","car",600,[["Aluminium_Pellet",13],["Steel_Pellet",11],["Windows",4],["Tyres",4]],1,60,0,""],
		["f_Taurus","A3PL_Taurus","car",600,[["Steel_Pellet",10],["Aluminium_Pellet",4],["Windows",4],["Tyres",4]],1,60,0,""],
		["f_Tahoe","A3PL_Tahoe","car",600,[["Steel_Pellet",11],["Aluminium_Pellet",7],["Windows",4],["Tyres",4]],1,60,0,""],
		["f_Suburban","A3PL_Suburban","car",600,[["Steel_Pellet",11],["Aluminium_Pellet",7],["Windows",4],["Tyres",4]],1,60,0,""],
		["f_Wrangler","A3PL_Wrangler","car",600,[["Steel_Pellet",7],["Aluminium_Pellet",2],["Windows",3],["Tyres",4]],1,60,0,""],
		["f_Rover","A3PL_Rover","car",1200,[["Steel_Pellet",12],["Aluminium_Pellet",27],["Windows",4],["Tyres",4]],1,120,0,""],
		["f_69Charger","A3PL_Charger69","car",300,[["Steel_Pellet",9],["Aluminium_Pellet",3],["Windows",4],["Tyres",4]],1,30,0,""],
		["f_Camaro","A3PL_Camaro","car",300,[["Steel_Pellet",8],["Aluminium_Pellet",3],["Windows",2],["Tyres",4]],1,30,0,""],
		["f_Charger","A3PL_Charger","car",900,[["Steel_Pellet",7],["Aluminium_Pellet",25],["Windows",2],["Tyres",4]],1,90,0,""],
		["f_Charger15","A3PL_Charger15","car",1200,[["Steel_Pellet",7],["Aluminium_Pellet",25],["Windows",2],["Tyres",4]],1,120,0,""],
		["f_BMW_X5","A3PL_BMW_X5","car",600,[["Steel_Pellet",11],["Aluminium_Pellet",22],["Windows",4],["Tyres",4]],1,60,0,""],
		["f_ZR1","A3PL_VetteZR1","car",1200,[["Steel_Pellet",18],["Aluminium_Pellet",17],["Titanium_Pellet",25],["Windows",4],["Tyres",4]],1,120,0,""],
		["f_Challenger_Hellcat","A3PL_Challenger_Hellcat","car",1200,[["Steel_Pellet",14],["Aluminium_Pellet",35],["Windows",4],["Tyres",4]],1,120,0,""],
		["f_Mustang","A3PL_Mustang","car",1200,[["Steel_Pellet",12],["Aluminium_Pellet",33],["Windows",4],["Tyres",4]],1,120,0,""],
		["f_BMW_M3","A3PL_BMW_M3","car",600,[["Steel_Pellet",9],["Aluminium_Pellet",7],["Windows",4],["Tyres",4]],1,60,0,""],
		["f_CLS63","A3PL_CLS63","car",1200,[["Steel_Pellet",10],["Aluminium_Pellet",13],["Windows",4],["Tyres",4]],1,120,0,""],
		["f_911GT2","A3PL_911GT2","car",1200,[["Steel_Pellet",18],["Aluminium_Pellet",17],["Titanium_Pellet",30],["Windows",4],["Tyres",4]],1,120,0,""],
		["f_Urus","A3PL_Urus","car",1200,[["Steel_Pellet",14],["Aluminium_Pellet",17],["Titanium_Pellet",20],["Windows",6],["Tyres",4]],1,120,0,""],
		["f_Gallardo","A3PL_Gallardo","car",1200,[["Steel_Pellet",14],["Aluminium_Pellet",17],["Titanium_Pellet",35],["Windows",6],["Tyres",4]],1,100,0,""],
		["f_Nissan_GTR","A3FL_Nissan_GTR","car",1200,[["Steel_Pellet",12],["Aluminium_Pellet",27],["Windows",4],["Tyres",4]],1,120,0,""],
		["f_Nissan_GTR_LW","A3FL_Nissan_GTR_LW","car",1500,[["Steel_Pellet",12],["Aluminium_Pellet",27],["Windows",4],["Tyres",4],["Titanium_Pellet",3]],1,120,0,""],
		["f_Smart_Car","A3FL_Smart_Car","car",300,[["Steel_Pellet",6],["Aluminium_Pellet",2],["Windows",4],["Tyres",4]],1,30,0,""],
		["f_BMW_M6","A3FL_BMW_M6","car",1200,[["Steel_Pellet",12],["Aluminium_Pellet",33],["Windows",4],["Tyres",4]],1,120,0,""],
		["f_Mercedes_Benz_AMG_C63","A3FL_Mercedes_Benz_AMG_C63","car",1200,[["Steel_Pellet",12],["Aluminium_Pellet",27],["Windows",4],["Tyres",4]],1,120,0,""],
		["f_Monster","A3PL_Monster","car",1200,[["Steel_Pellet",20],["Aluminium_Pellet",27],["Titanium_Pellet",9],["Windows",4],["Tyres",8]],1,80,0,""],
		["f_Kx","A3PL_Kx","car",600,[["Steel_Pellet",10],["Aluminium_Pellet",9],["Tyres",2]],1,60,0,""],
		["f_Fatboy","A3PL_Fatboy","car",1200,[["Steel_Pellet",10],["Aluminium_Pellet",10],["Titanium_Pellet",3],["Windows",1],["Tyres",2]],1,120,0,""],
		["f_Knucklehead","A3PL_Knucklehead","car",1200,[["Steel_Pellet",10],["Aluminium_Pellet",10],["Titanium_Pellet",3],["Windows",1],["Tyres",2]],1,120,0,""],
		["f_1100R","A3PL_1100R","car",1200,[["Steel_Pellet",10],["Aluminium_Pellet",15],["Titanium_Pellet",3],["Windows",1],["Tyres",2]],1,120,0,""],
		["f_mailtruck","A3PL_MailTruck","car",600,[["Steel_Pellet",9],["Aluminium_Pellet",1],["Windows",1],["Tyres",4]],1,60,0,""],
		["f_C_Van_02_transport_F","C_Van_02_transport_F","car",600,[["Steel_Pellet",13],["Aluminium_Pellet",6],["Windows",6],["Tyres",4]],1,60,0,""],
		["f_150_lb","A3PL_F150_Marker","car",900,[["Steel_Pellet",7],["Aluminium_Pellet",11],["Windows",4],["Tyres",4]],1,90,0,""],
		["f_Car_Trailer","A3PL_Car_Trailer","car",300,[["Steel_Pellet",4],["Aluminium_Pellet",1],["Tyres",4]],1,30,0,""],
		["f_Mini_Excavator","A3PL_MiniExcavator","car",900,[["Steel_Pellet",12],["Aluminium_Pellet",7],["Windows",1],["Tyres",4]],1,90,0,""],
		["f_Fuel_van","A3PL_Fuel_Van","car",900,[["Steel_Pellet",5],["Aluminium_Pellet",5],["Tyres", 4],["Windows", 2]],1,90,0,""],
		["f_p362","A3PL_P362","car",900,[["Steel_Pellet",20],["Aluminium_Pellet",8],["Windows",3],["Tyres",6]],1,90,0,""],
		["f_Tow_Truck","A3PL_P362_TowTruck","car",900,[["Steel_Pellet",14],["Aluminium_Pellet",5],["Windows",2],["Tyres",6]],1,90,0,""],
		["f_t370","A3FL_T370","car",900,[["Steel_Pellet",27],["Aluminium_Pellet",10],["Windows",3],["Tyres",6]],1,90,0,""],
		["f_t440","A3FL_T440","car",900,[["Steel_Pellet",36],["Aluminium_Pellet",10],["Windows",3],["Tyres",10]],1,90,0,""],
		["f_t440_Tow_Truck","A3FL_T440_Tow_Truck","car",900,[["Steel_Pellet",28],["Aluminium_Pellet",10],["Windows",2],["Tyres",10]],1,90,0,""],
		["f_t440_Gas_Tanker","A3FL_T440_Gas_Tanker","car",900,[["Steel_Pellet",25],["Aluminium_Pellet",9],["Windows",3],["Tyres",10]],1,90,0,""],
		["f_Lowloader","A3PL_Lowloader","car",300,[["Steel_Pellet",6],["Aluminium_Pellet",1],["Tyres",6]],1,30,0,""],
		["f_Small_boat_trailer","A3PL_Small_Boat_Trailer","car",300,[["Steel_Pellet",4],["Aluminium_Pellet",1],["Tyres",2]],1,30,0,""],
		["f_Drill_Trailer","A3PL_Drill_Trailer","car",300,[["Steel_Pellet",2],["Tyres",2]],1,30,0,""],
		["f_Tanker_Trailer","A3PL_Tanker_Trailer","car",300,[["Steel_Pellet",5],["Aluminium_Pellet",1],["Tyres",4]],1,30,0,""],
		["f_Box_Trailer","A3PL_Box_Trailer","car",300,[["Steel_Pellet",6],["Aluminium_Pellet",1],["Tyres",6]],1,30,0,""]
	],

	["Clothing Factory",[3345.15,7503.76,1.5],
		["f_A3PL_Indelicato_Family_Uniform","A3PL_Indelicato_Family_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_HF_Charter_Polo_Uniform","A3PL_HF_Charter_Polo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_RL_Polo_LBluBla_Uniform","A3PL_RL_Polo_LBluBla_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_RL_Polo_OranBla_Uniform","A3PL_RL_Polo_OranBla_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Target_Polo_Uniform","A3PL_Target_Polo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_ASSCPink_Uniform","A3PL_ASSCPink_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_ASSCCamo_Uniform","A3PL_ASSCCamo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_A3PL_TwoFours_Uniform","A3PL_TwoFours_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_A3PL_TwoFoursFatigues_Uniform","A3PL_TwoFoursFatigues_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FICP_Basic_Uniform","A3PL_FICP_Basic_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FICP_CEO_Uniform","A3PL_FICP_CEO_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FICP_COO_Uniform","A3PL_FICP_COO_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FICP_Legal_Uniform","A3PL_FICP_Legal_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FICP_Security_Uniform","A3PL_FICP_Security_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_CaseyLogistics_Uniform","A3PL_CaseyLogistics_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_CaseyLogistics_Mgr_Uniform","A3PL_CaseyLogistics_Mgr_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_CaseyLogistics_CEO_Uniform","A3PL_CaseyLogistics_CEO_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_CaseyLogistics_CFO_Uniform","A3PL_CaseyLogistics_CFO_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_CaseyLogistics_Foun_Uniform","A3PL_CaseyLogistics_Foun_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Veloucci_Family_Man","A3PL_Veloucci_Family_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Dep_Uniform_Man","A3PL_Dep_Uniform_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_High_Society_Uniform","A3PL_High_Society_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Daniel_Uniform","A3PL_Daniel_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Nike_Black_Uniform","A3PL_Nike_Black_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Eatsleep_Uniform","A3PL_Eatsleep_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FartLoading_Uniform","A3PL_FartLoading_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_GotGuns_Uniform","A3PL_GotGuns_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Muscleman_Uniform","A3PL_Muscleman_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_obeykitty_Uniform","A3PL_obeykitty_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_trump_Uniform","A3PL_trump_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_snakeskin_Uniform","A3PL_snakeskin_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_mcFishers_Uniform","A3PL_mcFishers_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Overload_Uniform","A3PL_Overload_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Lion_Like1_Uniform","A3PL_Lion_Like1_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Lion_Like2_Uniform","A3PL_Lion_Like2_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Lion_Like3_Uniform","A3PL_Lion_Like3_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Lion_Like4_Uniform","A3PL_Lion_Like4_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Lion_Like5_Uniform","A3PL_Lion_Like5_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Lion_Like6_Uniform","A3PL_Lion_Like6_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Lion_Like7_Uniform","A3PL_Lion_Like7_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Lion_Like8_Uniform","A3PL_Lion_Like8_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Lion_Like9_Uniform","A3PL_Lion_Like9_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Lion_Like10_Uniform","A3PL_Lion_Like10_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_The_Ranger_Uniform","A3PL_The_Ranger_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Oil_Recovery_Uniform","A3PL_Oil_Recovery_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Wildcatter_Uniform","A3PL_Wildcatter_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Worker_Uniform","A3PL_Worker_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_citizen2_Uniform","A3PL_citizen2_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_citizen3_Uniform","A3PL_citizen3_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_citizen4_Uniform","A3PL_citizen4_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_citizen5_Uniform","A3PL_citizen5_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Featherlite_Xmas","A3PL_featherlite_xmas_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Featherlite_Red","A3PL_featherlite_red_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Featherlite_Blue","A3PL_featherlite_blue_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Featherlite_Green","A3PL_featherlite_green_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Featherlite_Pink","A3PL_featherlite_pink_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Nikos","A3PL_Nikos_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_diver_Uniform","A3PL_Wetsuit_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_whitepolo_Uniform","A3PL_WhitePolo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_orangesportswear_Uniform","A3PL_Orange_Sportswear_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_surfingsportswear_Uniform","A3PL_Surfing_Sportswear_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_bluesportswear_Uniform","A3PL_Blue_Sportswear_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_greenstripe_Uniform","A3PL_GreenStripe_Polo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_bluestripe_Uniform","A3PL_BlueStripe_Polo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_twotoneblue_Uniform","A3PL_TwoTone_Blue_Polo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_bluepoloshorts_Uniform","A3PL_BluePolo_Shorts_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_journalist_Uniform","A3PL_Journalist_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_hunter_Uniform","A3PL_Hunter_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_dbluetshirt_Uniform","A3PL_DBlue_Tshirt_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_orangetshirt_Uniform","A3PL_Orange_Tshirt_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_greenpladshirt_Uniform","A3PL_GreenPlad_Shirt_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_dbluebutton_Uniform","A3PL_DBlue_ButtonUp_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_greenlsweater_Uniform","A3PL_GreenL_Sweater_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_camobandage_Uniform","A3PL_CamoBandage_Tshirt_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_crazyskull_Uniform","A3PL_CrazySkull_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_brownshirt_Uniform","A3PL_Brown_Shirt_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_sleevelessdirty_Uniform","A3PL_Sleeveless_Dirty_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_bandwdress_Uniform","A3PL_Bandw_DirtyDress_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_I_G_Story_Protagonist_F","U_I_G_Story_Protagonist_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Poor_1","U_C_Poor_1","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_WorkerCoveralls","U_C_WorkerCoveralls","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_B_survival_uniform","A3PL_Survival_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Man_casual_5_F","U_C_Man_casual_5_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Man_casual_4_F","U_C_Man_casual_4_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Man_casual_6_F","U_C_Man_casual_6_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_man_sport_2_F","U_C_man_sport_2_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_man_sport_3_F","U_C_man_sport_3_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_man_sport_1_F","U_C_man_sport_1_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_Rangemaster","U_Rangemaster","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_I_C_Soldier_Para_1_F","U_I_C_Soldier_Para_1_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_I_C_Soldier_Para_4_F","U_I_C_Soldier_Para_4_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_I_C_Soldier_Para_5_F","U_I_C_Soldier_Para_5_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_I_C_Soldier_Para_3_F","U_I_C_Soldier_Para_3_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_White_Dress","A3PL_White_Dress_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Nikos_Aged_Uniform","A3PL_Nikos_Aged_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_Marshal","U_Marshal","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Journalist","U_C_Journalist","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_OrestesBody","U_OrestesBody","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_HunterBody_grn","U_C_HunterBody_grn","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_BG_leader","U_BG_leader","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_BG_Guerilla3_1","U_BG_Guerilla3_1","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_BG_Guerilla2_3","U_BG_Guerilla2_3","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_BG_Guerilla2_1","U_BG_Guerilla2_1","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_BG_Guerilla2_2","U_BG_Guerilla2_2","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_BG_Guerilla1_1","U_BG_Guerilla1_1","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_BG_Guerrilla_6_1","U_BG_Guerrilla_6_1","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_B_GEN_Soldier_F","U_B_GEN_Soldier_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_B_GEN_Commander_F","U_B_GEN_Commander_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Driver_1_yellow","U_C_Driver_1_yellow","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Driver_1_white","U_C_Driver_1_white","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Driver_4","U_C_Driver_4","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Driver_3","U_C_Driver_3","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Driver_1_red","U_C_Driver_1_red","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Driver_1_orange","U_C_Driver_1_orange","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Driver_1_green","U_C_Driver_1_green","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Driver_1","U_C_Driver_1","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Driver_1_blue","U_C_Driver_1_blue","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Driver_1_black","U_C_Driver_1_black","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_Competitor","U_Competitor","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Poloshirt_tricolour","U_C_Poloshirt_tricolour","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Poloshirt_stripped","U_C_Poloshirt_stripped","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Poloshirt_salmon","U_C_Poloshirt_salmon","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Poloshirt_redwhite","U_C_Poloshirt_redwhite","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Poloshirt_burgundy","U_C_Poloshirt_burgundy","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Poloshirt_blue","U_C_Poloshirt_blue","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Man_casual_1_F","U_C_Man_casual_1_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Man_casual_3_F","U_C_Man_casual_3_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Man_casual_2_F","U_C_Man_casual_2_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_I_C_Soldier_Bandit_3_F","U_I_C_Soldier_Bandit_3_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_I_C_Soldier_Bandit_5_F","U_I_C_Soldier_Bandit_5_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_I_C_Soldier_Bandit_2_F","U_I_C_Soldier_Bandit_2_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_I_C_Soldier_Bandit_1_F","U_I_C_Soldier_Bandit_1_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_I_C_Soldier_Bandit_4_F","U_I_C_Soldier_Bandit_4_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_A3Moon","A3PL_A3Moon_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_ConstructionCoverall_Black_F","U_C_ConstructionCoverall_Black_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_ConstructionCoverall_Blue_F","U_C_ConstructionCoverall_Blue_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_ConstructionCoverall_Red_F","U_C_ConstructionCoverall_Red_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_ConstructionCoverall_Vrana_F","U_C_ConstructionCoverall_Vrana_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_U_C_Mechanic_01_F","U_C_Mechanic_01_F","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Hunting_Uniform","A3PL_Hunting_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Hoodie_Uniform","A3PL_Hoodie_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_TacoHell_Uniform","A3PL_TacoHell_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_DockWorker","A3PL_DockWorker_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Nike_SB","A3PL_Nike_SB_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Never_Fighting_Alone","A3PL_Never_Fighting_Alone_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Why_So_Friendly","A3PL_Why_So_Friendly_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_SuitBrwBlu_Uniform","A3PL_SuitBrwBlu_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_SuitGrnOra_Uniform","A3PL_SuitGrnOra_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_SuitRedTie_Uniform","A3PL_SuitRedTie_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_KHDesigns_Blue_Man","A3PL_KHDesigns_Blue_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_KHDesigns_Hawaii_Man","A3PL_KHDesigns_Hawaii_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_KHDesigns_Pink_Man","A3PL_KHDesigns_Pink_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_KHDesigns_Equality_Man","A3PL_KHDesigns_Equality_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Hazmat_Uniform","A3PL_Hazmat_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Blue_Suit_Jacket_Uniform","A3PL_Blue_Suit_Jacket_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_USCG_Veteran_Uniform","A3PL_USCG_Veteran_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Arma3_Uniform","A3PL_Arma3_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Empire","A3PL_Empire_Polo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Kings_Services","A3PL_Kings_Services_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_The_Kings_Uniform","A3PL_The_Kings_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_TriState_Fatigues_Uniform","A3PL_TriState_Fatigues_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Tri_State_uniform_Security_Uniform","A3PL_Tri_State_uniform_Security_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_GOLDEN_INDUSTRIES_Uniform","A3PL_GOLDEN_INDUSTRIES_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Australian_Defence_Uniform","A3PL_Australian_Defence_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Australian_Defence_RAAF_Uniform","A3PL_Australian_Defence_RAAF_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Army_OD_Uniform","A3PL_Army_OD_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_RAAF_Blue_Uniform","A3PL_RAAF_Blue_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Donald_Duck_Uniform","A3PL_Donald_Duck_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Xmas_Onesie_Red_Uniform","A3PL_Xmas_Onesie_Red_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Xmas_Onesie_Grey_Uniform","A3PL_Xmas_Onesie_Grey_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Supreme_Casual_Uniform","A3PL_Supreme_Casual_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Supreme_Casual_Logo_2_Uniform","A3PL_Supreme_Casual_Logo_2_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_LVPolo_Uniform","A3PL_LVPolo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_COD3_Employee_Uniform","A3PL_COD3_Employee_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_COD3_Supervisor_Uniform","A3PL_COD3_Supervisor_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Axel_Polo_Uniform","A3PL_Axel_Polo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Confession_Clothing_Uniform","A3PL_Confession_Clothing_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_CopsWatson_Uniform","A3PL_CopsWatson_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_woman4","woman4","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_woman3","woman3","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Woman_Uniform4","Woman_Uniform4","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Woman_Uniform3","Woman_Uniform3","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_woman2","woman2","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_woman1","woman1","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Woman_Uniform1","Woman_Uniform1","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Woman_Uniform2","Woman_Uniform2","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Journalist_Hardy","A3PL_Journalist_Hardy_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Two_Fours_Green","A3PL_Two_Fours_Green","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Evergreen_Polo","A3PL_Evergreen_Polo","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Evergreen_Coverall","A3PL_Evergreen_Coverall_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_PI_StreetWear_Man","A3PL_PI_StreetWear_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Boyd_Suit_Uniform","A3PL_Boyd_Suit_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Boyd_Combat_Uniform","A3PL_Boyd_Combat_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_MG_Watercraft_Uniform","A3PL_MG_Watercraft_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Infowars_Uniform","A3PL_Infowars_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_DHLSwimmer_Uniform","A3PL_DHLSwimmer_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Sorrento_Shirt_Uniform","A3PL_Sorrento_Shirt_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_StonedCombat_Uniform","A3PL_StonedCombat_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_COD3_Manager_Uniform","A3PL_COD3_Manager_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_COD3_CEO_Uniform","A3PL_COD3_CEO_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_COD3_CMO_Uniform","A3PL_COD3_CMO_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_COD3_COO_Uniform","A3PL_COD3_COO_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_COD3_CFO_Uniform","A3PL_COD3_CFO_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_COD3_Combat_Uniform","A3PL_COD3_Combat_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_COD3_Swimmer_Uniform","A3PL_COD3_Swimmer_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FICS_Trainee_Uniform","A3PL_FICS_Trainee_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FICS_Member_Uniform","A3PL_FICS_Member_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FICS_Supervisor_Uniform","A3PL_FICS_Supervisor_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FICS_Manager_Uniform","A3PL_FICS_Manager_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_FICS_Executive_Uniform","A3PL_FICS_Executive_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Watchful_Eyes_Hunter_Uniform","A3PL_Watchful_Eyes_Hunter_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Sorrento_Shirt_Uniform","A3PL_Sorrento_Shirt_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Axel_Swimmer_Uniform","A3PL_Axel_Swimmer_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_AI_Polo_Uniform","A3PL_AI_Polo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Construction_Uniform","A3PL_SmithCo_Construction_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Worker_Uniform","A3PL_SmithCo_Worker_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Polo_Plain_Uniform","A3PL_SmithCo_Polo_Plain_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Polo_Plain_Supervisor_Uniform","A3PL_SmithCo_Polo_Plain_Supervisor_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Polo_Pink_Uniform","A3PL_SmithCo_Polo_Pink_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Polo_Pink_Supervisor_Uniform","A3PL_SmithCo_Polo_Pink_Supervisor_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Polo_Security_Uniform","A3PL_SmithCo_Polo_Security_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Paramount_COO_Uniform","A3PL_Paramount_COO_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Paramount_CEO_Uniform","A3PL_Paramount_CEO_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_BL_Polo_Uniform","A3PL_BL_Polo_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Deadwood_Fatigues_Uniform","A3PL_Deadwood_Fatigues_Uniform","uniform",5,[["Polyester",1]],1,1,0,""],
		["f_Halstead_Uniform","A3PL_Halstead_Uniform","uniform",5,[["Polyester",1]],1,1,0,""]
	],

	["Vest Factory",[3345.15,7503.76,1.5],
		["f_A3PL_Holster_1","A3PL_Holster_1","vest",5,[["Polyester",1]],1,1,0,""],
		["f_BandollierB_blk","V_BandollierB_blk","vest",5,[["Steel",5]],1,1,0,""],
		["f_Press_F","A3PL_Press_Vest_F","vest",5,[["Steel",5]],1,1,0,""],
		["f_Rangemaster_belt_khk","A3PL_Rangemaster_belt","vest",5,[["Polyester",1],["Blueprint_Rangemaster_belt",1]],1,1,0,""],
		["f_Rangemaster_belt_blk","A3PL_Rangemaster_belt_blk","vest",5,[["Polyester",1],["Blueprint_Rangemaster_belt",1]],1,1,0,""],
		["f_V_Safety_blue_F","V_Safety_blue_F","vest",5,[["Polyester",1]],1,1,0,""],
		["f_V_Safety_orange_F","V_Safety_orange_F","vest",5,[["Polyester",1]],1,1,0,""],
		["f_V_Safety_yellow_F","V_Safety_yellow_F","vest",5,[["Polyester",1]],1,1,0,""],
		["f_Clean_Safety_Vest","A3PL_Clean_Safety_Vest","vest",5,[["Polyester",1]],1,1,0,""],
		["f_Clean_Safety_Vest_Orange","A3PL_Clean_Safety_Vest_Orange","vest",5,[["Polyester",1]],1,1,0,""],
		["f_Security_Safety_Orange","A3PL_Security_Safety_Orange","vest",5,[["Polyester",1]],1,1,0,""],
		["f_Security_HiVis_Vest","A3PL_Security_HiVis_Vest","vest",5,[["Polyester",1]],1,1,0,""],
		["f_Civilian_LifeVest","A3PL_Civilian_LifeVest","vest",5,[["Polyester",1]],1,1,0,""],
		["f_FakeNews_Safety","A3PL_FakeNews_Safety","vest",5,[["Polyester",1]],1,1,0,""],
		["f_Evergreen_Vest","A3PL_Evergreen_Vest","vest",5,[["Polyester",1]],1,1,0,""],
		["f_JoseConstruct_Safety_Vest","A3PL_JoseConstruct_Safety_Vest","vest",5,[["Polyester",1]],1,1,0,""],
		["f_AI_Safety_Vest","A3PL_AI_Safety_Vest","vest",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Safety_Vest","A3PL_SmithCo_Safety_Vest","vest",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Safety_Vest_Supervisor","A3PL_SmithCo_Safety_Vest_Supervisor","vest",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Safety_Vest_Security","A3PL_SmithCo_Safety_Vest_Security","vest",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Safety_Vest_Towing","A3PL_SmithCo_Safety_Vest_Towing","vest",5,[["Polyester",1]],1,1,0,""],
		["f_Deadwood_Member_Vest","A3PL_Deadwood_Member_Vest","vest",5,[["Polyester",1]],1,1,0,""],
		["f_Deadwood_Prospect_Vest","A3PL_Deadwood_Prospect_Vest","vest",5,[["Polyester",1]],1,1,0,""]
	],

	["Headgear Factory",[3345.15,7503.76,1.1],
		["f_Polo_Black_Cap","A3PL_Polo_Black_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Polo_LBlu_Cap","A3PL_Polo_LBlu_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Polo_Navy_Cap","A3PL_Polo_Navy_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Polo_Pink_Cap","A3PL_Polo_Pink_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Polo_Red_Cap","A3PL_Polo_Red_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Polo_Tan_Cap","A3PL_Polo_Tan_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Polo_White_Cap","A3PL_Polo_White_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_UA_Gray_Cap","A3PL_UA_Gray_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_UA_Blue_Cap","A3PL_UA_Blue_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_BackBlCamo_Cap","A3PL_BackBlCamo_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_UA_Camo_Cap","A3PL_UA_Camo_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_BackBl_UA_Cap","A3PL_BackBl_UA_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_UA_Black_Cap","A3PL_UA_Black_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_ASSC_Rose_Cap","A3PL_ASSC_Rose_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Nike_Black_Cap","A3PL_Nike_Black_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Back_Nike_Cap","A3PL_Back_Nike_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Adidas_Black_Cap","A3PL_Adidas_Black_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Back_Adidas_Cap","A3PL_Back_Adidas_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_A3PL_Canadian_Cap","A3PL_Canadian_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Security_Hat","A3PL_Security_Hat","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_FICP_Cap","A3PL_FICP_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_TriState_Security_Cap","A3PL_TriState_Security_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_BubblegumCheetas_Cap","A3PL_BubblegumCheetas_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Evergreen_Cap","A3PL_Evergreen_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_The_Kings_Cap","A3PL_The_Kings_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Australian_Defence_Cap","A3PL_Australian_Defence_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_RAAF_Cap","A3PL_RAAF_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_RAM_Cap","A3PL_RAM_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_CGVet_Cap","A3PL_CGVet_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Supreme_Fedora","A3PL_Supreme_Fedora","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Supreme_Cap","A3PL_Supreme_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Supreme_LV","A3PL_Supreme_LV","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Axel_Cap","A3PL_Axel_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Watchful_Eyes_Helmet","A3PL_Watchful_Eyes_Helmet","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Trump_Hat","A3PL_Trump_Hat","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_FFF_Hat","A3PL_FFF_Hat","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_USCG_Veteran_Cap","A3PL_USCG_Veteran_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_suferbandana_HeadGear","H_Bandanna_surfer","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_blkberet_HeadGear","H_Beret_blk","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_strawhat_HeadGear","H_StrawHat","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_oshemag_HeadGear","H_Shemag_olive","headgear",5,[["Polyester",1],["Blueprint_Shemag",1]],1,1,0,""],
		["f_tanshemag_HeadGear","H_Shemag_tan","headgear",5,[["Polyester",1],["Blueprint_Shemag",1]],1,1,0,""],
		["f_khkshemag_HeadGear","H_Shemag_khk","headgear",5,[["Polyester",1],["Blueprint_Shemag",1]],1,1,0,""],
		["f_skatehlmt_HeadGear","H_Helmet_Skate","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_booniekhk_HeadGear","H_Booniehat_khk","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_booniekhkhs_HeadGear","H_Booniehat_khk_hs","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_booniemcamo_HeadGear","H_Booniehat_mcamo","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_boonieoli_HeadGear","H_Booniehat_oli","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_boonietan_HeadGear","H_Booniehat_tan","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_booniedgtl_HeadGear","H_Booniehat_dgtl","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Booniehat_tna_F","H_Booniehat_tna_F","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Hat_Safari_Olive_F","H_Hat_Safari_Olive_F","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Hat_Safari_Olive_F","H_Hat_Safari_Olive_F","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_RacingHelmet_1","A3PL_RacingHelmet_1","headgear",5,[["Fibreglass",5]],1,1,0,""],
		["f_RacingHelmet_2","A3PL_RacingHelmet_2","headgear",5,[["Fibreglass",5]],1,1,0,""],
		["f_RacingHelmet_3","A3PL_RacingHelmet_3","headgear",5,[["Fibreglass",5]],1,1,0,""],
		["f_RacingHelmet_4","A3PL_RacingHelmet_4","headgear",5,[["Fibreglass",5]],1,1,0,""],
		["f_RacingHelmet_5","A3PL_RacingHelmet_5","headgear",5,[["Fibreglass",5]],1,1,0,""],
		["f_RacingHelmet_6","A3PL_RacingHelmet_6","headgear",5,[["Fibreglass",5]],1,1,0,""],
		["f_RacingHelmet_7","A3PL_RacingHelmet_7","headgear",5,[["Fibreglass",5]],1,1,0,""],
		["f_RacingHelmet_8","A3PL_RacingHelmet_8","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_RacingHelmet_9","A3PL_RacingHelmet_9","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_RacingHelmet_10","A3PL_RacingHelmet_10","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_RacingHelmet_11","A3PL_RacingHelmet_11","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_StrawHat_dark","H_StrawHat_dark","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_ShemagOpen_khk","H_ShemagOpen_khk","headgear",5,[["Polyester",1],["Blueprint_Shemag",1]],1,1,0,""],
		["f_H_ShemagOpen_tan","H_ShemagOpen_tan","headgear",5,[["Polyester",1],["Blueprint_Shemag",1]],1,1,0,""],
		["f_H_Shemag_olive_hs","H_Shemag_olive_hs","headgear",5,[["Polyester",1],["Blueprint_Shemag",1]],1,1,0,""],
		["f_H_MilCap_dgtl","H_MilCap_dgtl","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_MilCap_tna_F","H_MilCap_tna_F","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_MilCap_mcamo","H_MilCap_mcamo","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_MilCap_ocamo","H_MilCap_ocamo","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_MilCap_gry","H_MilCap_gry","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_MilCap_ghex_F","H_MilCap_ghex_F","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_MilCap_blue","H_MilCap_blue","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Fedora_Black","A3PL_Fedora_Black","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_LavendarRibbon_Fedora","A3PL_LavendarRibbon_Fedora","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Hat_tan","H_Hat_tan","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Hat_grey","H_Hat_grey","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Hat_checker","H_Hat_checker","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Hat_camo","H_Hat_camo","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Hat_brown","H_Hat_brown","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Hat_blue","H_Hat_blue","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_headphoneg_HeadGear","H_Cap_headphones","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_marshal_HeadGear","H_Cap_marshal","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_redhat_HeadGear","H_Cap_red","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_bluehat_HeadGear","H_Cap_blu","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_sufercap_HeadGear","H_cap_surfer","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_Black_Cap","A3PL_Black_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_brn_SPECOPS","H_Cap_brn_SPECOPS","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_blk_Raven","H_Cap_blk_Raven","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_tan_specops_US","H_Cap_tan_specops_US","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_usblack","H_Cap_usblack","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_khaki_specops_UK","H_Cap_khaki_specops_UK","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_tan","H_Cap_tan","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_press","H_Cap_press","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_oli_hs","H_Cap_oli_hs","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_oli","H_Cap_oli","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_blk_ION","H_Cap_blk_ION","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_grn","H_Cap_grn","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_blk_CMMG","H_Cap_blk_CMMG","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_blk","H_Cap_blk","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Cap_grn_BI","H_Cap_grn_BI","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Beret_Colonel","H_Beret_Colonel","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Beret_02","H_Beret_02","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Beret_gen_F","H_Beret_gen_F","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Watchcap_khk","H_Watchcap_khk","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Watchcap_camo","H_Watchcap_camo","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Watchcap_cbr","H_Watchcap_cbr","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Watchcap_blk","H_Watchcap_blk","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_camo","H_Bandanna_camo","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_surfer_grn","H_Bandanna_surfer_grn","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_surfer_blk","H_Bandanna_surfer_blk","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_sand","H_Bandanna_sand","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_sgg","H_Bandanna_sgg","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_mcamo","H_Bandanna_mcamo","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_khk","H_Bandanna_khk","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_khk_hs","H_Bandanna_khk_hs","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_cbr","H_Bandanna_cbr","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_blu","H_Bandanna_blu","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_Bandanna_gry","H_Bandanna_gry","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_EarProtectors_black_F","H_EarProtectors_black_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_EarProtectors_orange_F","H_EarProtectors_orange_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_EarProtectors_red_F","H_EarProtectors_red_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_EarProtectors_white_F","H_EarProtectors_white_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_EarProtectors_yellow_F","H_EarProtectors_yellow_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_basic_black_F","H_Construction_basic_black_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_earprot_black_F","H_Construction_earprot_black_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_headset_black_F","H_Construction_headset_black_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_basic_orange_F","H_Construction_basic_orange_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_earprot_orange_F","H_Construction_earprot_orange_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_headset_orange_F","H_Construction_headset_orange_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_basic_red_F","H_Construction_basic_red_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_earprot_red_F","H_Construction_earprot_red_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_headset_red_F","H_Construction_headset_red_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_basic_vrana_F","H_Construction_basic_vrana_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_earprot_vrana_F","H_Construction_earprot_vrana_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_headset_vrana_F","H_Construction_headset_vrana_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_basic_white_F","H_Construction_basic_white_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_earprot_white_F","H_Construction_earprot_white_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_headset_white_F","H_Construction_headset_white_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_basic_yellow_F","H_Construction_basic_yellow_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_earprot_yellow_F","H_Construction_earprot_yellow_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Construction_headset_yellow_F","H_Construction_headset_yellow_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_HeadBandage_clean_F","H_HeadBandage_clean_F","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_HeadBandage_stained_F","H_HeadBandage_stained_F","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_HeadBandage_bloody_F","H_HeadBandage_bloody_F","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_H_HeadSet_black_F","H_HeadSet_black_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_HeadSet_orange_F","H_HeadSet_orange_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_HeadSet_red_F","H_HeadSet_red_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_HeadSet_white_F","H_HeadSet_white_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_HeadSet_yellow_F","H_HeadSet_yellow_F","headgear",5,[["Plastic",1]],1,1,0,""],
		["f_H_Evergreen_Cap","A3PL_Evergreen_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_COD3_Cap","A3PL_COD3_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_AI_Cap","A3PL_AI_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Cap","A3PL_SmithCo_Cap","headgear",5,[["Polyester",1]],1,1,0,""],
		["f_SmithCo_Towing_Cap","A3PL_SmithCo_Towing_Cap","headgear",5,[["Polyester",1]],1,1,0,""]
	],

	["Goggle Factory",[3345.15,7503.76,1.1],
		["f_aviator_goggles","G_Aviator","goggles",5,[["Glass",1]],1,1,0,""],
		["f_square_goggles","G_Squares","goggles",5,[["Glass",1]],1,1,0,""],
		["f_squaretinted_goggles","G_Squares_Tinted","goggles",5,[["Glass",1]],1,1,0,""],
		["f_shadesblk_goggles","G_Shades_Black","goggles",5,[["Glass",1]],1,1,0,""],
		["f_shadesblue_goggles","G_Shades_Blue","goggles",5,[["Glass",1]],1,1,0,""],
		["f_shadesgrn_goggles","G_Shades_Green","goggles",5,[["Glass",1]],1,1,0,""],
		["f_shadesred_goggles","G_Shades_Red","goggles",5,[["Glass",1]],1,1,0,""],
		["f_spectacles_goggles","G_Spectacles","goggles",5,[["Glass",1]],1,1,0,""],
		["f_spectint_goggles","G_Spectacles_Tinted","goggles",5,[["Glass",1]],1,1,0,""],
		["f_sportred_goggles","G_Sport_Red","goggles",5,[["Glass",1]],1,1,0,""],
		["f_sportbw_goggles","G_Sport_BlackWhite","goggles",5,[["Glass",1]],1,1,0,""],
		["f_sportblkred_goggles","G_Sport_Blackred","goggles",5,[["Glass",1]],1,1,0,""],
		["f_sportgrnblk_goggles","G_Sport_Greenblack","goggles",5,[["Glass",1]],1,1,0,""],
		["f_tactclr_goggles","G_Tactical_Clear","goggles",5,[["Glass",1]],1,1,0,""],
		["f_tactblk_goggles","G_Tactical_Black","goggles",5,[["Glass",1]],1,1,0,""],
		["f_balaclava_goggles","G_Balaclava_blk","goggles",5,[["Polyester",1],["Blueprint_balaclava",1]],1,1,0,""],
		["f_balaclavacom_goggles","G_Balaclava_combat","goggles",5,[["Polyester",1],["Blueprint_balaclava",1]],1,1,0,""],
		["f_balaclavatna_goggles","G_Balaclava_TI_G_tna_F","goggles",5,[["Polyester",1],["Blueprint_balaclava",1]],1,1,0,""],
		["f_balaclavalopro_goggles","G_Balaclava_lowprofile","goggles",5,[["Glass",1],["Blueprint_balaclava",1]],1,1,0,""],
		["f_balaclavaoli_goggles","G_Balaclava_oli","goggles",5,[["Polyester",1],["Blueprint_balaclava",1]],1,1,0,""],
		["f_G_Balaclava_TI_tna_F","G_Balaclava_TI_tna_F","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_Balaclava_TI_G_blk_F","G_Balaclava_TI_G_blk_F","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_Balaclava_TI_blk_F","G_Balaclava_TI_blk_F","goggles",5,[["Glass",1]],1,1,0,""],
		["f_Skull_Mask","A3PL_Skull_Mask","goggles",5,[["Glass",1]],1,1,0,""],
		["f_Watchdogs_Mask","A3PL_Watchdogs_Mask","goggles",5,[["Glass",1]],1,1,0,""],
		["f_Bandanna_aviator","G_Bandanna_aviator","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_Bandanna_blue_aviator ","G_Bandanna_blue_aviator","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_Bandanna_orange_aviator","G_Bandanna_orange_aviator","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_Bandanna_pink_aviator","G_Bandanna_pink_aviator","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_Bandanna_red_aviator","G_Bandanna_red_aviator","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_Bandanna_maroon_aviator","G_Bandanna_maroon_aviator","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_Bandanna_white_aviator","G_Bandanna_white_aviator","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_Bandanna_yellow_aviator","G_Bandanna_yellow_aviator","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_Bandanna_black_aviator","G_Bandanna_black_aviator","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_Bandanna_beast","G_Bandanna_beast","goggles",5,[["Polyester",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_Bandanna_blk","G_Bandanna_blk","goggles",5,[["Polyester",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_G_Bandanna_oli","G_Bandanna_oli","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_G_Bandanna_shades","G_Bandanna_shades","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_G_Bandanna_khk","G_Bandanna_khk","goggles",5,[["Glass",1],["Blueprint_Bandanna",1]],1,1,0,""],
		["f_G_Combat_Goggles_tna_F","G_Combat_Goggles_tna_F","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_Bandanna_tan","G_Bandanna_tan","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_Bandanna_sport","G_Bandanna_sport","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_Goggles_VR","G_Goggles_VR","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_Lowprofile","G_Lowprofile","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_Lady_Blue","G_Lady_Blue","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_Diving","G_Diving","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_EyeProtectors_F","G_EyeProtectors_F","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_EyeProtectors_Earpiece_F","G_EyeProtectors_Earpiece_F","goggles",5,[["Glass",1]],1,1,0,""],
		["f_G_Respirator_blue_F","G_Respirator_blue_F","goggles",5,[["Polyester",1]],1,1,0,""],
		["f_G_Respirator_white_F","G_Respirator_white_F","goggles",5,[["Polyester",1]],1,1,0,""],
		["f_G_Respirator_yellow_F","G_Respirator_yellow_F","goggles",5,[["Polyester",1]],1,1,0,""]
	],

	["Faction Equipment",[3852.065,9212.537,0.168],
		["f_bloodbag","medS_bloodbag","item",0,[],1,0,0,""],
		["f_bandage","med_bandage","item",0,[],1,0,0,""],
		["f_icepack","med_icepack","item",0,[],1,0,0,""],
		["f_painkillers","med_painkillers","item",0,[],1,0,0,""],
		["f_autograft","med_autograft","item",0,[],1,0,0,""],
		["f_med_narcan","med_narcan","item",0,[],1,0,0,""],
		["f_cast","med_cast","item",0,[],1,0,0,""],
		["f_endotracheal","med_endotracheal","item",0,[],1,0,0,""],
		["f_kit","med_kit","item",0,[],1,0,0,""],
		["f_oxygenmask","med_oxygenmask","item",0,[],1,0,0,""],
		["f_splint","med_splint","item",0,[],1,0,0,""],
		["f_FD_yAdapter","FD_yAdapter","item",0,[],1,0,0,""],
		["f_FD_Adapter","FD_Adapter","item",0,[],1,0,0,""],
		["f_FD_Hose","FD_Hose","item",0,[],1,0,0,""],
		["f_FD_FireNozzle","A3PL_High_Pressure","weapon",0,[],1,0,0,""],
		["f_FD_HydrantWrench","FD_HydrantWrench","item",0,[],1,0,0,""],
		["f_FDaxe","A3PL_FireAxe","weapon",0,[],1,0,0,""],
		["f_Jaws","A3PL_Jaws","weapon",0,[],1,0,0,""],
		["f_roadcones","roadcones","item",0,[],1,0,0,""],
		["f_breathalizer","breathalizer","item",0,[],1,0,0,""],
		["f_drug_kit","drug_kit","item",0,[],1,0,0,""],
		["f_Handcuffs","handcuffs","item",0,[],1,0,0,""],
		["f_stinger","stinger","item",0,[],1,0,0,""]
	],

	["Faction Clothing Factory",[0,0,0],
		["f_USCG_Hat_Logo_Text","A3PL_USCG_Hat_Logo_Text","headgear",0,[],1,0,0,""],
		["f_USCG_Boat_Helmet_Test","A3PL_USCG_Boat_Helmet_Test","headgear",0,[],1,0,0,""],
		["f_coast_guard_cgis","A3PL_coast_guard_cgis","headgear",0,[],1,0,0,""],
		["f_USCG_PublicAff_Cap","A3PL_USCG_PublicAff_Cap","headgear",0,[],1,0,0,""],
		["f_CGAS_Hat","A3PL_CGAS_Hat","headgear",0,[],1,0,0,""],
		["f_MSRT_Hat","A3PL_MSRT_Hat","headgear",0,[],1,0,0,""],
		["f_JAG_Hat","A3PL_JAG_Hat","headgear",0,[],1,0,0,""],
		["f_MSRT_Helmet","A3PL_MSRT_Helmet","headgear",0,[],1,0,0,""],
		["f_MSRT_BLMC_Helmet","A3PL_MSRT_BLMC_Helmet","headgear",0,[],1,0,0,""],
		["f_SWRebel_Pilot","A3PL_SWRebel_Pilot","headgear",0,[],1,0,0,""],
		["f_HelloKitty_Pilot","A3PL_HelloKitty_Pilot","headgear",0,[],1,0,0,""],
		["f_USCG_Blue_White_Pilot_Helm","A3PL_USCG_Blue_White_Pilot_Helm","headgear",0,[],1,0,0,""],
		["f_USCG_White_Red_Pilot_Helm","A3PL_USCG_White_Red_Pilot_Helm","headgear",0,[],1,0,0,""],
		["f_USCG_Green_White_Pilot_Helm","A3PL_USCG_Green_White_Pilot_Helm","headgear",0,[],1,0,0,""],
		["f_USCG_Red_White_Pilot_Helm","A3PL_USCG_Red_White_Pilot_Helm","headgear",0,[],1,0,0,""],
		["f_USCG_Grey_White_Pilot_Helm","A3PL_USCG_Grey_White_Pilot_Helm","headgear",0,[],1,0,0,""],
		["f_USCG_Crew_Helmet","A3PL_USCG_Crew_Helmet","headgear",0,[],1,0,0,""],
		["f_USCG_Seaman_Recruit_Uniform","A3PL_USCG_Seaman_Recruit_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Seaman_Uniform","A3PL_USCG_Seaman_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Petty_Officer_Uniform","A3PL_USCG_Petty_Officer_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Chief_Petty_Officer_Uniform","A3PL_USCG_Chief_Petty_Officer_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Master_Chief_Petty_Officer_Uniform","A3PL_USCG_Master_Chief_Petty_Officer_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Ensign_Uniform","A3PL_USCG_Ensign_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Lieutenant_JG_Uniform","A3PL_USCG_Lieutenant_JG_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Lt_Uniform","A3PL_USCG_Lt_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Lt_Commander_Uniform","A3PL_USCG_Lt_Commander_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Commander_Uniform","A3PL_USCG_Commander_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Shirt_NR_Uniform","A3PL_USCG_Shirt_NR_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Shirt_CPO_Uniform","A3PL_USCG_Shirt_CPO_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Shirt_MCPO_Uniform","A3PL_USCG_Shirt_MCPO_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Shirt_Ensign_Uniform","A3PL_USCG_Shirt_Ensign_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Shirt_LieutenantJ_Uniform","A3PL_USCG_Shirt_LieutenantJ_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Shirt_Lieutenant_Uniform","A3PL_USCG_Shirt_Lieutenant_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Shirt_LieutenantCommander_Uniform","A3PL_USCG_Shirt_LieutenantCommander_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Shirt_Commander_Uniform","A3PL_USCG_Shirt_Commander_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Rescue_Swimmer_Uniform","A3PL_USCG_Rescue_Swimmer_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_MSRT_Uniform","A3PL_USCG_MSRT_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_CGIS_Uniform_Uniform","A3PL_USCG_CGIS_Uniform_Uniform","uniform",0,[],1,0,0,""],
		["f_JAG_Suit_Uniform","A3PL_JAG_Suit_Uniform","uniform",0,[],1,0,0,""],
		["f_MSRT_BLMC_Uniform","A3PL_MSRT_BLMC_Uniform","uniform",0,[],1,0,0,""],
		["f_MSRT_BLMC_Trial_Uniform","A3PL_MSRT_BLMC_Trial_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Aviation_Seaman_Uniform","A3PL_USCG_Aviation_Seaman_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Aviation_PO_Uniform","A3PL_USCG_Aviation_PO_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Aviation_CPO_Uniform","A3PL_USCG_Aviation_CPO_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Aviation_MCPO_Uniform","A3PL_USCG_Aviation_MCPO_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Aviation_Ensign_Uniform","A3PL_USCG_Aviation_Ensign_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Aviation_LtJG_Uniform","A3PL_USCG_Aviation_LtJG_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Aviation_Lt_Uniform","A3PL_USCG_Aviation_Lt_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Aviation_LCDR_Uniform","A3PL_USCG_Aviation_LCDR_Uniform","uniform",0,[],1,0,0,""],
		["f_USCG_Aviation_CDR_Uniform","A3PL_USCG_Aviation_CDR_Uniform","uniform",0,[],1,0,0,""],
		["f_DutyBelt","A3PL_DutyBelt","vest",0,[],1,0,0,""],
		["f_Holster_1","A3PL_Holster_1","vest",0,[],1,0,0,""],
		["f_USCG_LifeVest","A3PL_USCG_LifeVest","vest",0,[],1,0,0,""],
		["f_CGVest_BLUE","A3PL_CGVest_BLUE","vest",0,[],1,0,0,""],
		["f_CGPSU_Vest","A3PL_CGPSU_Vest","vest",0,[],1,0,0,""],
		["f_USCG_Rig_Lite","A3PL_USCG_Rig_Lite","vest",0,[],1,0,0,""],
		["f_MSRT_Vest_Black_Lite","A3PL_MSRT_Vest_Black_Lite","vest",0,[],1,0,0,""],
		["f_MSRT_Vest_Mlcam_Lite","A3PL_MSRT_Vest_Mlcam_Lite","vest",0,[],1,0,0,""],
		["f_MSRT_Vest_BLMC_Lite","A3PL_MSRT_Vest_BLMC_Lite","vest",0,[],1,0,0,""],
		["f_RebreatherB","V_RebreatherB","vest",0,[],1,0,0,""],
		["f_USCG_Ground_Safety_Vest","A3PL_USCG_Ground_Safety_Vest","vest",0,[],1,0,0,""],
		
		["f_FIFR_Cap_VibrantBlue_Hat","A3PL_FIFR_Cap_VibrantBlue_Hat","headgear",0,[],1,0,0,""],
		["f_FIFR_Cap_White_Hat","A3PL_FIFR_Cap_White_Hat","headgear",0,[],1,0,0,""],
		["f_FIFR_Cap_Red_Hat","A3PL_FIFR_Cap_Red_Hat","headgear",0,[],1,0,0,""],
		["f_FIFR_Cap_Orange_Hat","A3PL_FIFR_Cap_Orange_Hat","headgear",0,[],1,0,0,""],
		["f_FIFR_Cap_Navy_Hat","A3PL_FIFR_Cap_Navy_Hat","headgear",0,[],1,0,0,""],
		["f_FIFR_Cap_Black_Hat","A3PL_FIFR_Cap_Black_Hat","headgear",0,[],1,0,0,""],
		["f_FIFR_Cap_HotPinki_Hat","A3PL_FIFR_Cap_HotPinki_Hat","headgear",0,[],1,0,0,""],
		["f_FIFR_Cap_Lt_Hat","A3PL_FIFR_Cap_Lt_Hat","headgear",0,[],1,0,0,""],
		["f_FIFR_Cap_Command_Black_Hat","A3PL_FIFR_Cap_Command_Black_Hat","headgear",0,[],1,0,0,""],
		["f_FIFR_Cap_Safety_Hat","A3PL_FIFR_Cap_Safety_Hat","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Probationer_New","A3PL_FireHelmet_Probationer_New","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Firefighter_New","A3PL_FireHelmet_Firefighter_New","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Engineer_New","A3PL_FireHelmet_Engineer_New","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Lieutenant_New","A3PL_FireHelmet_Lieutenant_New","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Captain_New","A3PL_FireHelmet_Captain_New","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Batt_1_New","A3PL_FireHelmet_Batt_1_New","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Batt_2_New","A3PL_FireHelmet_Batt_2_New","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Dep_Chief_New","A3PL_FireHelmet_Dep_Chief_New","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Chief_New","A3PL_FireHelmet_Chief_New","headgear",0,[],1,0,0,""],
		["f_FIFR_Flight_Para_Helm","A3PL_FIFR_Flight_Para_Helm","headgear",0,[],1,0,0,""],
		["f_FIFR_Pilot_Helm","A3PL_FIFR_Pilot_Helm","headgear",0,[],1,0,0,""],
		["f_Volunteer_FD_Cap","A3PL_Volunteer_FD_Cap","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Firefighter_New","A3PL_FireHelmet_Firefighter_New","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Engineer_New","A3PL_FireHelmet_Engineer_New","headgear",0,[],1,0,0,""],
		["f_FireHelmet_Lieutenant_New","A3PL_FireHelmet_Lieutenant_New","headgear",0,[],1,0,0,""],
		["f_FIFR_STUDENT_Uniform","A3PL_FIFR_STUDENT_Uniform","uniform",0,[],1,0,0,""],
		["f_FIFR_EMT_Uniform","A3PL_FIFR_EMT_Uniform","uniform",0,[],1,0,0,""],
		["f_FIFR_Paramedic_Uniform","A3PL_FIFR_Paramedic_Uniform","uniform",0,[],1,0,0,""],
		["f_FIFR_Engineer_Uniform","A3PL_FIFR_Engineer_Uniform","uniform",0,[],1,0,0,""],
		["f_FIFR_Lieutenant_Uniform","A3PL_FIFR_Lieutenant_Uniform","uniform",0,[],1,0,0,""],
		["f_FIFR_Bat_Chief_Uniform","A3PL_FIFR_Bat_Chief_Uniform","uniform",0,[],1,0,0,""],
		["f_FIFR_Fire_DeputyChief_Uniform","A3PL_FIFR_Fire_DeputyChief_Uniform","uniform",0,[],1,0,0,""],
		["f_FIFR_Fire_Chief_Uniform","A3PL_FIFR_Fire_Chief_Uniform","uniform",0,[],1,0,0,""],
		["f_Air_Ambulance_Pilot_Uniform","A3PL_Air_Ambulance_Pilot_Uniform","uniform",0,[],1,0,0,""],
		["f_Air_Ambulance_Paramedic_Uniform","A3PL_Air_Ambulance_Paramedic_Uniform","uniform",0,[],1,0,0,""],
		["f_FIFR_PR_Uniform","A3PL_FIFR_PR_Uniform","uniform",0,[],1,0,0,""],
		["f_FD_Protective_Uniform","A3PL_FD_Protective_Uniform","uniform",0,[],1,0,0,""],
		["f_VFD_Lieutenant_Uniform","A3PL_VFD_Lieutenant_Uniform","uniform",0,[],1,0,0,""],
		["f_VFD_Engineer_Uniform","A3PL_VFD_Engineer_Uniform","uniform",0,[],1,0,0,""],
		["f_VFD_Firefighter_Uniform","A3PL_VFD_Firefighter_Uniform","uniform",0,[],1,0,0,""],
		["f_FIFR_RideAlong_Safety","A3PL_FIFR_RideAlong_Safety","vest",0,[],1,0,0,""],
		["f_FIFR_Safety","A3PL_FIFR_Safety","vest",0,[],1,0,0,""],
		["f_FIFR_Student_Safety","A3PL_FIFR_Student_Safety","vest",0,[],1,0,0,""],
		["f_FIFR_Safety_EMT","A3PL_FIFR_Safety_EMT","vest",0,[],1,0,0,""],
		["f_FIFR_Safety_Fire","A3PL_FIFR_Safety_Fire","vest",0,[],1,0,0,""],
		["f_FIFR_Safety_Paramedic","A3PL_FIFR_Safety_Paramedic","vest",0,[],1,0,0,""],
		["f_FIFR_Safety_Lieutenant","A3PL_FIFR_Safety_Lieutenant","vest",0,[],1,0,0,""],
		["f_FIFR_Safety_Command","A3PL_FIFR_Safety_Command","vest",0,[],1,0,0,""],
		["f_Air_Ambulance_EMT_Vest","A3PL_Air_Ambulance_EMT_Vest","vest",0,[],1,0,0,""],
		["f_Air_Ambulance_Paramedic_Vest","A3PL_Air_Ambulance_Paramedic_Vest","vest",0,[],1,0,0,""],
		["f_Air_Ambulance_Pilot_Vest","A3PL_Air_Ambulance_Pilot_Vest","vest",0,[],1,0,0,""],
		["f_FIFR_Public_Relations_vest","A3PL_FIFR_Public_Relations_vest","vest",0,[],1,0,0,""],
		["f_FD_Oxygen","A3PL_FD_Oxygen","vest",0,[],1,0,0,""],
		["f_VFD_Vest","A3PL_VFD_Vest","vest",0,[],1,0,0,""],
		["f_VFD_IC_Vest","A3PL_VFD_IC_Vest","vest",0,[],1,0,0,""],
		
		["f_Sheriff_Black_Cap","A3PL_Sheriff_Black_Cap","headgear",0,[],1,0,0,""],
		["f_Sheriff_Campaign_Hat_Grey","A3PL_Sheriff_Campaign_Hat_Grey","headgear",0,[],1,0,0,""],
		["f_Sheriff_Grey_Cap","A3PL_Sheriff_Grey_Cap","headgear",0,[],1,0,0,""],
		["f_Sheriff_ERTGrn_Cap","A3PL_Sheriff_ERTGrn_Cap","headgear",0,[],1,0,0,""],
		["f_Back_FISD_ERT_Cap","A3PL_Back_FISD_ERT_Cap","headgear",0,[],1,0,0,""],
		["f_SD_ERT_Green_Test_Helm","A3PL_SD_ERT_Green_Test_Helm","headgear",0,[],1,0,0,""],
		["f_FISD_Grey_Pilot_Helm","A3PL_FISD_Grey_Pilot_Helm","headgear",0,[],1,0,0,""],
		["f_FISD_White_Pilot_Helm","A3PL_FISD_White_Pilot_Helm","headgear",0,[],1,0,0,""],
		["f_SD_NR_Tan_Uniform","A3PL_SD_NR_Tan_Uniform","uniform",0,[],1,0,0,""],
		["f_SD_Cad_Tan_Uniform","A3PL_SD_Cad_Tan_Uniform","uniform",0,[],1,0,0,""],
		["f_SD_Dep_Tan_Uniform","A3PL_SD_Dep_Tan_Uniform","uniform",0,[],1,0,0,""],
		["f_SD_SDep_Tan_Uniform","A3PL_SD_SDep_Tan_Uniform","uniform",0,[],1,0,0,""],
		["f_SD_Sgt_Tan_Uniform","A3PL_SD_Sgt_Tan_Uniform","uniform",0,[],1,0,0,""],
		["f_SD_LT_Tan_Uniform","A3PL_SD_LT_Tan_Uniform","uniform",0,[],1,0,0,""],
		["f_SD_Capt_Tan_Uniform","A3PL_SD_Capt_Tan_Uniform","uniform",0,[],1,0,0,""],
		["f_SD_Und_Sh_Tan_Uniform","A3PL_SD_Und_Sh_Tan_Uniform","uniform",0,[],1,0,0,""],
		["f_SD_Sh_Tan_Uniform","A3PL_SD_Sh_Tan_Uniform","uniform",0,[],1,0,0,""],
		["f_ERT_Fatigues_Uniform","A3PL_ERT_Fatigues_Uniform","uniform",0,[],1,0,0,""],
		["f_Detective_WhiTan_Uniform","A3PL_Detective_WhiTan_Uniform","uniform",0,[],1,0,0,""],
		["f_Detective_BluTan_Uniform","A3PL_Detective_BluTan_Uniform","uniform",0,[],1,0,0,""],
		["f_SD_MCU_Swimmer_Uniform","A3PL_SD_MCU_Swimmer_Uniform","uniform",0,[],1,0,0,""],
		["f_FISD_Pilot_Uniform","A3PL_FISD_Pilot_Uniform","uniform",0,[],1,0,0,""],
		["f_FISD_Safety_Traffic","A3PL_FISD_Safety_Traffic","vest",0,[],1,0,0,""],
		["f_DutyBelt","A3PL_DutyBelt","vest",0,[],1,0,0,""],
		["f_Holster_1","A3PL_Holster_1","vest",0,[],1,0,0,""],
		["f_Sheriff_Rig_Test","A3PL_Sheriff_Rig_Test","vest",0,[],1,0,0,""],
		["f_SD_Rig_ERT","A3PL_SD_Rig_ERT","vest",0,[],1,0,0,""],
		["f_SD_ERTGreen_Vest_Test","A3PL_SD_ERTGreen_Vest_Test",0,[],1,0,0,""],
		["f_SD_Rig_K9","A3PL_SD_Rig_K9","vest",0,[],1,0,0,""],
		["f_SD_Rig_HW","A3PL_SD_Rig_HW","vest",0,[],1,0,0,""],
		["f_SD_Detective_Vest_Lite","A3PL_SD_Detective_Vest_Lite","vest",0,[],1,0,0,""],
		["f_SD_Rig","A3PL_SD_Rig","vest",0,[],1,0,0,""],
		["f_SD_Rig_Air","A3PL_SD_Rig_Air","vest",0,[],1,0,0,""],
		["f_SD_High_Threat_Lite","A3PL_SD_High_Threat_Lite","vest",0,[],1,0,0,""],
		
		["f_DOJ_Hat","A3PL_DOJ_Hat","headgear",0,[],1,0,0,""],
		["f_DOJ_Blk_Hat","A3PL_DOJ_Blk_Hat","headgear",0,[],1,0,0,""],
		["f_DOJ_Blu_Hat","A3PL_DOJ_Blu_Hat","headgear",0,[],1,0,0,""],
		["f_DOJ_DBlue_Uniform","A3PL_DOJ_DBlue_Uniform","uniform",0,[],1,0,0,""],
		["f_DOJ_LBlue_Uniform","A3PL_DOJ_LBlue_Uniform","uniform",0,[],1,0,0,""],
		["f_DOJ_Purp_Uniform","A3PL_DOJ_Purp_Uniform","uniform",0,[],1,0,0,""],
		["f_CJ_Polo_Uniform","A3PL_CJ_Polo_Uniform","uniform",0,[],1,0,0,""],
		["f_ACJ_Polo_Uniform","A3PL_ACJ_Polo_Uniform","uniform",0,[],1,0,0,""],
		["f_J_Polo_Uniform","A3PL_J_Polo_Uniform","uniform",0,[],1,0,0,""],
		["f_Judy_Polo_Uniform","A3PL_Judy_Polo_Uniform","uniform",0,[],1,0,0,""],
		["f_DOJ_Blk_Suit_Uniform","A3PL_DOJ_Blk_Suit_Uniform","uniform",0,[],1,0,0,""],
		["f_DOJ_Blu_Suit_Uniform","A3PL_DOJ_Blu_Suit_Uniform","uniform",0,[],1,0,0,""],
		["f_DOJ_Grn_Suit_Uniform","A3PL_DOJ_Grn_Suit_Uniform","uniform",0,[],1,0,0,""],
		["f_DOJ_Red_Suit_Uniform","A3PL_DOJ_Red_Suit_Uniform","uniform",0,[],1,0,0,""],
		["f_DOJ_Yel_Suit_Uniform","A3PL_DOJ_Yel_Suit_Uniform","uniform",0,[],1,0,0,""],
		["f_DOJ_Black_VEST","A3PL_DOJ_Black_VEST","vest",0,[],1,0,0,""],
		["f_DOJ_Black_TacVest","A3PL_DOJ_Black_TacVest",0,[],1,0,0,""],
		["f_DOJ_CJ_Vest","A3PL_DOJ_CJ_Vest","vest",0,[],1,0,0,""],
		["f_DOJ_ACJ_Vest","A3PL_DOJ_ACJ_Vest","vest",0,[],1,0,0,""],
		["f_DOJ_J_Vest","A3PL_DOJ_J_Vest","vest",0,[],1,0,0,""],
		["f_DOJ_Judy_Vest","A3PL_DOJ_Judy_Vest","vest",0,[],1,0,0,""],
		
		["f_US_Marshall_Cap","A3PL_US_Marshall_Cap","headgear",0,[],1,0,0,""],
		["f_US_Marshall_SOG_Cap","A3PL_US_Marshall_SOG_Cap","headgear",0,[],1,0,0,""],
		["f_Back_FIMS_SOG_Cap","A3PL_Back_FIMS_SOG_Cap","headgear",0,[],1,0,0,""],
		["f_Marshal_SOG_Helmet","A3PL_Marshal_SOG_Helmet","headgear",0,[],1,0,0,""],
		["f_doc_green_Uniform","A3PL_doc_green_Uniform","uniform",0,[],1,0,0,""],
		["f_doc_blue_Uniform","A3PL_doc_blue_Uniform","uniform",0,[],1,0,0,""],
		["f_doc_yellow_Uniform","A3PL_doc_yellow_Uniform","uniform",0,[],1,0,0,""],
		["f_doc_orange_Uniform","A3PL_doc_orange_Uniform","uniform",0,[],1,0,0,""],
		["f_doc_red_Uniform","A3PL_doc_red_Uniform","uniform",0,[],1,0,0,""],
		["f_doc_pink_Uniform","A3PL_doc_pink_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_Cadet_Uniform","A3PL_FI_Marshal_Cadet_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_Marshal_Uniform","A3PL_FI_Marshal_Marshal_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_SeniorMarshal_Uniform","A3PL_FI_Marshal_SeniorMarshal_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_Supervisor_Uniform","A3PL_FI_Marshal_Supervisor_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_HeadMarshal_Uniform","A3PL_FI_Marshal_HeadMarshal_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_DeputyDirector_Uniform","A3PL_FI_Marshal_DeputyDirector_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_Director_Uniform","A3PL_FI_Marshal_Director_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_SOG_Uniform","A3PL_FI_Marshal_SOG_Casual_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_SOG_Cadet_Uniform","A3PL_FI_Marshal_SOG_Casual_Cadet_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_SOG_Marshal_Uniform","A3PL_FI_Marshal_SOG_Casual_Marshal_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_SOG_SeniorM_Uniform","A3PL_FI_Marshal_SOG_Casual_SeniorM_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_SOG_Supervisor_Uniform","A3PL_FI_Marshal_SOG_Casual_Supervisor_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_SOG_HeadM_Uniform","A3PL_FI_Marshal_SOG_Casual_HeadM_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_SOG_DptyD_Uniform","A3PL_FI_Marshal_SOG_Casual_DptyD_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshal_SOG_Director_Uniform","A3PL_FI_Marshal_SOG_Casual_Director_Uniform","uniform",0,[],1,0,0,""],
		["f_Marshall_FGTF_Uniform","A3PL_Marshall_FGTF_Uniform","uniform",0,[],1,0,0,""],
		["f_FIMS_SOG_Swimmer_Uniform","A3PL_FIMS_SOG_Swimmer_Uniform","uniform",0,[],1,0,0,""],
		["f_FIMS_DBlue_Uniform","A3PL_FIMS_DBlue_Uniform","uniform",0,[],1,0,0,""],
		["f_FIMS_LBlue_Uniform","A3PL_FIMS_LBlue_Uniform","uniform",0,[],1,0,0,""],
		["f_FIMS_DPurp_Uniform","A3PL_FIMS_DPurp_Uniform","uniform",0,[],1,0,0,""],
		["f_FIMS_LPurp_Uniform","A3PL_FIMS_LPurp_Uniform","uniform",0,[],1,0,0,""],
		["f_FIMS_Peach_Uniform","A3PL_FIMS_Peach_Uniform","uniform",0,[],1,0,0,""],
		["f_FIMS_Pink_Uniform","A3PL_FIMS_Pink_Uniform","uniform",0,[],1,0,0,""],
		["f_FIMS_Red_Uniform","A3PL_FIMS_Red_Uniform","uniform",0,[],1,0,0,""],
		["f_Rangemaster_belt_blk","A3PL_Rangemaster_belt_blk","vest",0,[],1,0,0,""],
		["f_US_Marshall_Blk_Lite","A3PL_US_Marshall_Blk_Lite","vest",0,[],1,0,0,""],
		["f_US_Marshall_SOG_Lite","A3PL_US_Marshall_SOG_Lite","vest",0,[],1,0,0,""]
	],

	["Faction Vehicles",[0,0,0],
		["f_f450","jonzie_ambulance","car",0,[],1,0,0,""],
		["f_e350","A3PL_E350","car",0,[],1,0,0,""],
		["f_tahoe_FD","A3PL_Tahoe_FD","car",0,[],1,0,0,""],
		["f_ladder","A3PL_Pierce_Ladder","car",0,[],1,0,0,""],
		["f_hladder","A3PL_Pierce_Heavy_Ladder","car",0,[],1,0,0,""],
		["f_pumper","A3PL_Pierce_Pumper","car",0,[],1,0,0,""],
		["f_rescue","A3PL_Pierce_Rescue","car",0,[],1,0,0,""],
		["f_cvpi_PD","A3PL_CVPI_PD","car",0,[],1,0,0,""],
		["f_cvpi_PDST","A3PL_CVPI_PD_Slicktop","car",0,[],1,0,0,""],
		["f_taurus_PD","A3PL_Taurus_PD","car",0,[],1,0,0,""],
		["f_taurus_PD_ST","A3PL_Taurus_PD_ST","car",0,[],1,0,0,""],
		["f_charger15_PD","A3PL_Charger15_PD","car",0,[],1,0,0,""],
		["f_charger15_PD_ST","A3PL_Charger15_PD_ST","car",0,[],1,0,0,""],
		["f_tahoe_PD","A3PL_Tahoe_PD","car",0,[],1,0,0,""],
		["f_tahoe_PDST","A3PL_Tahoe_PD_Slicktop","car",0,[],1,0,0,""],
		["f_charger_PD","A3PL_Charger_PD","car",0,[],1,0,0,""],
		["f_charger_PDST","A3PL_Charger_PD_Slicktop","car",0,[],1,0,0,""],
		["f_Silverado_PD","A3PL_Silverado_PD","car",0,[],1,0,0,""],
		["f_Silverado_PD_ST","A3PL_Silverado_PD_ST","car",0,[],1,0,0,""],
		["f_Mustang_PD","A3PL_Mustang_PD","car",0,[],1,0,0,""],
		["f_mustang_PDST","A3PL_Mustang_PD_Slicktop","car",0,[],1,0,0,""],
		["f_Explorer_Platinum_PD_20","A3FL_Explorer_Platinum_PD_20","car",0,[],1,0,0,""],
		["f_Explorer_Platinum_PD_Slicktop_20","A3FL_Explorer_Platinum_PD_Slicktop_20","car",0,[],1,0,0,""],
		["f_Explorer_Platinum_FD_20","A3FL_Explorer_Platinum_FD_20","car",0,[],1,0,0,""],
		["f_CG_Heli","Heli_Medium01_Coastguard_H","plane",0,[],1,0,0,""],
		["f_Jayhawk_USCG","A3PL_Jayhawk","plane",0,[],1,0,0,""],
		["f_AS_365","A3FL_AS_365","plane",0,[],1,0,0,""],
		["f_Medic_Heli","Heli_Medium01_Medic_H","plane",0,[],1,0,0,""],
		["f_Sheriff_Heli","Heli_Medium01_Sheriff_H","plane",0,[],1,0,0,""],
		["f_RBM","A3PL_RBM","car",0,[],1,0,0,""]
	],

	["Faction Weapons",[0,0,0],
		["f_Shield","A3FL_Shield","weapon",0,[],1,0,0,""],
		["f_Shield_FIMS","A3FL_Shield_FIMS","weapon",0,[],1,0,0,""],
		["f_Pistol_Signal","hgun_Pistol_Signal_F",0,[],1,0,0,""],
		["f_Taser","A3PL_Taser","weapon",0,[],1,0,0,""],
		["f_Taser2","A3PL_Taser2","weapon",0,[],1,0,0,""],
		["f_PepperSpray","A3FL_PepperSpray","weapon",0,[],1,0,0,""],
		["f_Rook40","hgun_Rook40_F","weapon",0,[],1,0,0,""],
		["f_P226","A3PL_P226","weapon",0,[],1,0,0,""],
		["f_P227","A3FL_P227","weapon",0,[],1,0,0,""],
		["f_Glock17","A3FL_Glock17","weapon",0,[],1,0,0,""],
		["f_Glock18","A3FL_Glock18","weapon",0,[],1,0,0,""],
		["f_Beretta92","A3FL_Beretta92","weapon",0,[],1,0,0,""],
		["f_SMG_05_F","SMG_05_F","weapon",0,[],1,0,0,""],
		["f_UMP","A3FL_UMP","weapon",0,[],1,0,0,""],
		["f_Mossberg_590K","A3FL_Mossberg_590k","weapon",0,[],1,0,0,""],
		["f_A3FL_M4","A3FL_M4","weapon",0,[],1,0,0,""],
		["f_A3PL_M16","A3PL_M16","weapon",0,[],1,0,0,""],
		["f_srifle_LRR_SOS_F","srifle_LRR_SOS_F","weapon",0,[],1,0,0,""],
		["f_6Rnd_GreenSignal_Mag","6Rnd_GreenSignal_F","magazine",0,[],1,0,0,""],
		["f_6Rnd_RedSignal_Mag","6Rnd_RedSignal_F","magazine",0,[],1,0,0,""],
		["f_TaserMag","A3PL_TaserMag","magazine",0,[],1,0,0,""],
		["f_Taser2_Mag","A3PL_Taser2_Mag","magazine",0,[],1,0,0,""],
		["f_P226_Mag","A3PL_P226_Mag","magazine",0,[],1,0,0,""],
		["f_P227_Mag","A3FL_P227_Mag","magazine",0,[],1,0,0,""],
		["f_Glock17_Mag","A3FL_Glock17_Mag","magazine",0,[],1,0,0,""],
		["f_Glock18_Mag","A3FL_Glock18_Mag","magazine",0,[],1,0,0,""],
		["f_Beretta92_Mag","A3FL_Beretta92_Mag","magazine",0,[],1,0,0,""],
		["f_16Rnd_9x21_Mag","16Rnd_9x21_Mag","magazine",0,[],1,0,0,""],
		["f_30Rnd_9x21_Mag_SMG_02","30Rnd_9x21_Mag_SMG_02","magazine",0,[],10,0,0,""],
		["f_UMP_Mag","A3FL_UMP_Mag","magazine",0,[],1,0,0,""],
		["f_Mossberg_590K_Beanbag","A3FL_Mossberg_590K_Beanbag","magazine",0,[],1,0,0,""],
		["f_Mossberg_590K_8rnd_buck","A3FL_Mossberg_590K_8rnd_buck","magazine",0,[],1,0,0,""],
		["f_Mossberg_590K_8rnd_Breach","A3FL_Mossberg_590K_8rnd_Breach","magazine",0,[],1,0,0,""],
		["f_A3PL_M16_Mag","A3PL_M16_Mag","magazine",0,[],1,0,0,""],
		["f_7Rnd_408_Mag","7Rnd_408_Mag","magazine",0,[],1,0,0,""],
		["f_acc_flashlight_pistol","acc_flashlight_pistol","aitem",0,[],1,0,0,""],
		["f_acc_flashlight","acc_flashlight","aitem",0,[],1,0,0,""],
		["f_Mossberg_590K_Flashlight","A3FL_Mossberg_590K_Flashlight","aitem",0,[],1,0,0,""],
		["f_optic_aco_smg","optic_aco_smg","aitem",0,[],1,0,0,""],
		["f_optic_Holosight_smg_blk_F","optic_Holosight_smg_blk_F","aitem",0,[],1,0,0,""]
	],

	["Admin Tools",[0,0,0],
		["f_FBI_Suit_Tie_Uniform","A3PL_FBI_Suit_Tie_Uniform","uniform",0,[],1,0,0,""],
		["f_FBI_Agent_Blue_Uniform","A3PL_FBI_Agent_Blue_Uniform","uniform",0,[],1,0,0,""],
		["f_FBI_Agent_Tan_Uniform","A3PL_FBI_Agent_Tan_Uniform","uniform",0,[],1,0,0,""],
		["f_FBI_Trainee","A3PL_FBI_Trainee","vest",0,[],1,0,0,""],
		["f_FBI_Executive","A3PL_FBI_Executive","vest",0,[],1,0,0,""],
		["f_FBI_Supervisor","A3PL_FBI_Supervisor","vest",0,[],1,0,0,""],
		["f_FBI_Chief","A3PL_FBI_Chief","vest",0,[],1,0,0,""],
		["f_FBI_SubDirector","A3PL_FBI_SubDirector","vest",0,[],1,0,0,""],
		["f_FBI_Director","A3PL_FBI_Director","vest",0,[],1,0,0,""],
		["f_FBI_Ballcap3","A3PL_FBI_Ballcap3","headgear",0,[],1,0,0,""],
		["f_gift","gift","item",0,[],1,0,0,""],
		["f_ItemGPS","ItemGPS","aitem",0,[],1,0,0,""],
		["f_ItemMap","ItemMap","aitem",0,[],1,0,0,""],
		["f_life_alert","life_alert","item",0,[],1,0,0,""],
		["f_drill_bit","drill_bit","item",0,[],1,0,0,""],
		["f_Backpack_Drill","A3PL_Backpack_Drill","backpack",0,[],1,0,0,""],
		["f_Backpack_Money","A3PL_Backpack_Money","backpack",0,[],1,0,0,""],
		["f_keycard","keycard","item",0,[],1,0,0,""],
		["f_beer","beer","item",0,[],1,0,0,""],
		["f_sand","sand","item",0,[],1,0,0,""],
		["f_Aluminium_Ore","Aluminium_Ore","item",0,[],1,0,0,""],
		["f_Sulphur_Ore","Sulphur_Ore","item",0,[],1,0,0,""],
		["f_Iron_Ore","Iron_Ore","item",0,[],1,0,0,""],
		["f_Coal_Ore","Coal_Ore","item",0,[],1,0,0,""],
		["f_Sapphire_Ore","Sapphire_Ore","item",0,[],1,0,0,""],
		["f_Vivianite_Ore","Vivianite_Ore","item",0,[],1,0,0,""],
		["f_Emerald_Ore","Emerald_Ore","item",0,[],1,0,0,""],
		["f_Gold_Ore","Gold_Ore","item",0,[],1,0,0,""],
		["f_Amethyst_Ore","Amethyst_Ore","item",0,[],1,0,0,""],
		["f_diamond_emerald","diamond_emerald","item",0,[],1,0,0,""],
		["f_diamond_sapphire","diamond_sapphire","item",0,[],1,0,0,""],
		["f_diamond_aqua","diamond_aqua","item",0,[],1,0,0,""],
		["f_diamond_alex","diamond_alex","item",0,[],1,0,0,""],
		["f_diamond_ruby","diamond_ruby","item",0,[],1,0,0,""],
		["f_diamond_tourmaline","diamond_tourmaline","item",0,[],1,0,0,""],
		["f_diamond","diamond","item",0,[],1,0,0,""],
		["f_seed_marijuana","seed_marijuana","item",0,[],1,0,0,""],
		["f_cannabis_bud","cannabis_bud","item",0,[],1,0,0,""],
		["f_cannabis_bud_cured","cannabis_bud_cured","item",0,[],1,0,0,""],
		["f_cannabis_grinded_5g","cannabis_grinded_5g","item",0,[],1,0,0,""],
		["f_weed_100g","weed_100g","item",0,[],1,0,0,""],
		["f_cocaine","cocaine","item",0,[],1,0,0,""],
		["f_scale","scale","item",0,[],1,0,0,""],
		["f_fan","fan","item",0,[],1,0,0,""],
		["f_grinder","grinder","item",0,[],1,0,0,""],
		["f_planter","planter","item",0,[],1,0,0,""],
		["f_lamp_200w","lamp_200w","item",0,[],1,0,0,""],
		["f_lamp_500w","lamp_500w","item",0,[],1,0,0,""],
		["f_lamp_1000w","lamp_1000w","item",0,[],1,0,0,""],
		["f_pavilion","pavilion","item",0,[],1,0,0,""],
		["f_workbench","workbench","item",0,[],1,0,0,""],
		["f_cocaine_barrel","cocaine_barrel","item",0,[],1,0,0,""],
		["f_sulphuric_acid","sulphuric_acid","item",0,[],1,0,0,""],
		["f_calcium_carbonate","calcium_carbonate","item",0,[],1,0,0,""],
		["f_potassium_permangate","potassium_permangate","item",0,[],1,0,0,""],
		["f_ammonium_hydroxide","ammonium_hydroxide","item",0,[],1,0,0,""],
		["f_acetone","acetone","item",0,[],1,0,0,""],
		["f_hydrocloric_acid","hydrocloric_acid","item",0,[],1,0,0,""],
		["f_coca_paste","coca_paste","item",0,[],1,0,0,""],
		["f_cocaine_base","cocaine_base","item",0,[],1,0,0,""],
		["f_cocaine_hydrochloride","cocaine_hydrochloride","item",0,[],1,0,0,""],
		["f_cocaine_brick","cocaine_brick","item",0,[],1,0,0,""],
		["f_shrooms","shrooms","item",0,[],1,0,0,""],
		["f_distillery","distillery","item",0,[],1,0,0,""],
		["f_distillery_hose","distillery_hose","item",0,[],1,0,0,""],
		["f_jug","jug","item",0,[],1,0,0,""],
		["f_jug_green","jug_green","item",0,[],1,0,0,""],
		["f_jug_moonshine","jug_moonshine","item",0,[],1,0,0,""],
		["f_diamond_emerald_ill","diamond_emerald_ill","item",0,[],1,0,0,""],
		["f_diamond_sapphire_ill","diamond_sapphire_ill","item",0,[],1,0,0,""],
		["f_diamond_aqua_ill","diamond_aqua_ill","item",0,[],1,0,0,""],
		["f_diamond_alex_ill","diamond_alex_ill","item",0,[],1,0,0,""],
		["f_diamond_ruby_ill","diamond_ruby_ill","item",0,[],1,0,0,""],
		["f_diamond_tourmaline_ill","diamond_tourmaline_ill","item",0,[],1,0,0,""],
		["f_diamond_ill","diamond_ill","item",0,[],1,0,0,""],
		["f_ring","ring","item",0,[],1,0,0,""],
		["f_ringset","ringset","item",0,[],1,0,0,""],
		["f_bracelet","bracelet","item",0,[],1,0,0,""],
		["f_crown","crown","item",0,[],1,0,0,""],
		["f_necklace","necklace","item",0,[],1,0,0,""],
		["f_golden_dildo","golden_dildo","item",0,[],1,0,0,""],
		["f_bucket_full","bucket_full","item",0,[],1,0,0,""],
		["f_shark_2lb","shark_2lb","item",0,[],1,0,0,""],
		["f_shark_4lb","shark_4lb","item",0,[],1,0,0,""],
		["f_shark_5lb","shark_5lb","item",0,[],1,0,0,""],
		["f_shark_7lb","shark_7lb","item",0,[],1,0,0,""],
		["f_shark_10lb","shark_10lb","item",0,[],1,0,0,""],
		["f_burger_cooked","burger_cooked","item",0,[],1,0,0,""],
		["f_fish_cooked","fish_cooked","item",0,[],1,0,0,""],
		["f_seed_corn","seed_corn","item",0,[],5,0,0,""],
		["f_seed_wheat","seed_wheat","item",0,[],5,0,0,""],
		["f_seed_lettuce","seed_lettuce","item",0,[],5,0,0,""],
		["f_seed_coca","seed_coca","item",0,[],5,0,0,""],
		["f_seed_sugar","seed_sugar","item",0,[],5,0,0,""],
		["f_wheat","wheat","item",0,[],5,0,0,""],
		["f_corn","corn","item",0,[],5,0,0,""],
		["f_lettuce","lettuce","item",0,[],5,0,0,""],
		["f_Burger","burger_full_cooked","item",0,[],5,0,0,""],
		["f_Taco","taco_cooked","item",0,[],5,0,0,""],
		["f_meatpie","meatpie","item",0,[],5,0,0,""],
		["f_waterbottle","waterbottle","item",0,[],5,0,0,""],
		["f_mullet","mullet","item",0,[],5,0,0,""],
		["f_matches","matches","item",0,[],5,0,0,""],
		["f_jerrycan","jerrycan","item",0,[],1,0,0,""],
		["f_jerrycan_empty","jerrycan_empty","item",0,[],1,0,0,""],
		["f_zipties","zipties","item",0,[],1,0,0,""],
		["f_v_lockpick","v_lockpick","item",0,[],1,0,0,""],
		["f_Paintball_Marker","A3PL_Paintball_Marker","weapon",60,[],1,0,1,""],
		["f_Paintball_Mag","A3PL_Paintball_Mag","magazine",60,[],10,0,0,""],
		["f_Pickaxe","A3PL_Pickaxe","weapon",60,[],1,0,0,""],
		["f_Shovel","A3PL_Shovel","weapon",60,[],1,0,0,""],
		["f_GolfDriver","A3FL_GolfDriver","weapon",60,[],1,0,0,""],
		["f_BaseballBat","A3FL_BaseballBat","weapon",60,[],1,0,0,""],
		["f_Cellphone","A3PL_Cellphone","aitem",0,[],1,0,0,""],
		["f_anprc152","tfar_anprc152","aitem",0,[],1,0,0,""],
		["f_LR","A3PL_LR","backpack",0,[],1,0,0,""]
	]
];
publicVariable "Config_Factories";